* Республика Волмарт
06.01.2021
5/10
Пустые размышления о прелести планирования, ни приличного матанализа, ни доказательной базы. Антисоветчина и досужие домослы

* Град бреченный 
Стругацкие
12.01.2021
3/10
Дерьмо помазанное дерьмом, рассизм и страпрдское брюзжание. Никаких свежих идей

* Маленький принц
Экзюпери
28.01.2021
5/10
Пиздострадания. Походу мне уже не по размеру такие книжки. 

* Сумма технологий
Лем
07.02.2021
9/10
Шикарно. Вся современная научная фантастика, это жалкая копия этой книжки. Рекомендую всем.

* Обмен разумов
Шеели
10.02.2021
6/10
Такое себе

* Город и город
Мьенвиль
7/10
22.02.2021
Неплохо. Следак который копал слишком хорошо

* Дюна 1
7/10
07.03.2021
Гораздо интереснее фильмов

* Марсеане
Робинсон
6/10
31.03.2021
Приятно встретится с старыми знакомыми, но рватый стиль все портит

* Красная луна
Робинсон
6/10
18.04.2021
Не очень интересно, ничего нового. Еще и китайцы кругом

* НьюЦорн 2214
Робинсон
7/10
01.05.2021

* Аврора
Робинсон
8/10
04.05.2021

* Сами боги
Азимов
9/10
13.06.2021
Довольно иньересно, но самое главное, что это одна история во всех его произведенрях

* Азимов Рассказы
Я Робот
7/10
18.06.2021

* Семиевие
Нил стивенсон
7/10
24.06.2021
Интересно и познавательно. Но как легкий технобоевичек.

 
