* Jan
** 001 01.01.2021 Пт
*** Ледяные цветы
Абсолютно все зашито в ледяно понцирь. Туман осаждает на деревьях и цветах иней и они превращаются в ледяные цветы. Каждый раз выходя из дома попадаешь в зимнюю сказку.  
*** Сериальчики
Занимали день сегодня безудержным просмотром сериалов. Один безинтереснее другого. В это время каждый занимался своим делом. Мама разгадывала сканворды, Димка играл в Факторио, я читал книжку. Папа спал.  
*** Реклама
От безделья понесло меня в Ютуб на телефоне. О ужас. Я узрел рекламу. Это отвратительная мерзость. Как люди вообще сидят не в Опере. Блаженные в своем неведении люди смотрят ютуб с этой рекламой. Я то думал, что мерзость, это когда ведущие непосредственно рекламят свякие игрушки и голосом рассказывают как они там что-то делают, но это было лишь вершиной айсберга. Ютуб сам суют каждые 5 минут левую рекламу - это ужасно. Жду недождусь, когда вернусь к просмотру ютубчика в Опере.  
*** План А
Начал читать "Республика Волмарт" и это вызвало у меня прямые асоциации для лого одной из моих групп. По приезду к нормальному компу надо будет перерисовать в нормальных скруглениямх и цеветах. Но пока пятилучевая звездочка (мир без звездочек) и градиент перехода (как в загрузке (только я ошибся и нарисовал градиент в другую сторону). Символизируют загрузку новой SocOS.  
** 002 02.01.2021 Сб
*** Отвертка
Просятил Димук, что в Никоновских объективах морочкик в фотике и крутится там отвертка. Почему они такие дорогие, мы не придумали.  
*** Снежки
Димка пошел приклеивать градусник и зарядил снежки в рабицу. Получились прикольные дыры в ледяном панцире сетки. Выглядело более чем эффектно.  
*** Чтиво
Практически весь день придавался чтению Волмарта. Не Стивенсон конечно, но годнота.  
*** Сериальчик
Посмотрели Звездный путь. Кругом сплошная политкоректота, но с фантастической точки зрения никакой.  
** 003 03.01.2021 Вс
*** Арома
Обновил еще один балон масляной мяты, разлил балон спиртовой мяты и балон дегтя. Может показаться странным, но это работает (пока не доказано обратное).  
*** Горизонт
Когда поехали, были прикольные виды с снежными тучами и самосветящимся горизонтом. Четкое разделение неба и земли застовило задуматься "как давно я вообще видел горизонт". Деревья в ледяных панцирях и грязная дорога.  
*** Непрядва
Заехали за Катей. Там бабская суета и Леша жарит шашлык. Катя набрала тяжеленную сумку. Степка уже указывает, что надо закрыть дверь. Все хорошо. Мама просила сфотать речку.  
*** Тула
Приехали. Тут грязища. Скука скучная и единстенное развлечение - компьютер. Надо переводить этот инструмент из разряда развлечений в дело.  
*** Дугин
Это прекрасно. Посмотрел НГ обращение Дугина на Авроре и просто катался по полу от смеха. Один из немногих русских философов современности цитирует мемасики и призывает читать классиков. Он шикарен.  
** 004 04.01.2021 Пн
*** Отпросилась
*** Работа
*** Семейные ценности
*** Чтение
*** Макадамия
*** Перехват
*** Вибрация
*** Тыква раздора

