* Jan
** 01.01.2021 Пт
*** Ледяные цветы
Абсолютно все зашито в ледяно понцирь. Туман осаждает на деревьях и цветах иней и они превращаются в ледяные цветы. Каждый раз выходя из дома попадаешь в зимнюю сказку.  
*** Сериальчики
Занимали день сегодня безудержным просмотром сериалов. Один безинтереснее другого. В это время каждый занимался своим делом. Мама разгадывала сканворды, Димка играл в Факторио, я читал книжку. Папа спал.  
*** Реклама
От безделья понесло меня в Ютуб на телефоне. О ужас. Я узрел рекламу. Это отвратительная мерзость. Как люди вообще сидят не в Опере. Блаженные в своем неведении люди смотрят ютуб с этой рекламой. Я то думал, что мерзость, это когда ведущие непосредственно рекламят свякие игрушки и голосом рассказывают как они там что-то делают, но это было лишь вершиной айсберга. Ютуб сам суют каждые 5 минут левую рекламу - это ужасно. Жду недождусь, когда вернусь к просмотру ютубчика в Опере.  
*** План А
Начал читать "Республика Волмарт" и это вызвало у меня прямые асоциации для лого одной из моих групп. По приезду к нормальному компу надо будет перерисовать в нормальных скруглениямх и цеветах. Но пока пятилучевая звездочка (мир без звездочек) и градиент перехода (как в загрузке (только я ошибся и нарисовал градиент в другую сторону). Символизируют загрузку новой SocOS.  
** 02.01.2021 Сб
*** Отвертка
Просятил Димук, что в Никоновских объективах морочкик в фотике и крутится там отвертка. Почему они такие дорогие, мы не придумали.  
*** Снежки
Димка пошел приклеивать градусник и зарядил снежки в рабицу. Получились прикольные дыры в ледяном панцире сетки. Выглядело более чем эффектно.  
*** Чтиво
Практически весь день придавался чтению Волмарта. Не Стивенсон конечно, но годнота.  
*** Сериальчик
Посмотрели Звездный путь. Кругом сплошная политкоректота, но с фантастической точки зрения никакой.  
** 03.01.2021 Вс
*** Арома
Обновил еще один балон масляной мяты, разлил балон спиртовой мяты и балон дегтя. Может показаться странным, но это работает (пока не доказано обратное).  
*** Горизонт
Когда поехали, были прикольные виды с снежными тучами и самосветящимся горизонтом. Четкое разделение неба и земли застовило задуматься "как давно я вообще видел горизонт". Деревья в ледяных панцирях и грязная дорога.  
*** Непрядва
Заехали за Катей. Там бабская суета и Леша жарит шашлык. Катя набрала тяжеленную сумку. Степка уже указывает, что надо закрыть дверь. Все хорошо. Мама просила сфотать речку.  
*** Тула
Приехали. Тут грязища. Скука скучная и единстенное развлечение - компьютер. Надо переводить этот инструмент из разряда развлечений в дело.  
*** Дугин
Это прекрасно. Посмотрел НГ обращение Дугина на Авроре и просто катался по полу от смеха. Один из немногих русских философов современности цитирует мемасики и призывает читать классиков. Он шикарен.  
** 04.01.2021 Пн
*** Отпросилась
Погда я еще спал, но уже успел заварить чаек и залезть в ВК, мне написала И, и сообщила, что не придет сегодня, и ей слишком лениво. Я что-то прям расстроился и решил пойти в спортивной одежде и вообще отмести любые приличия и деградировать. Я удручен.  
*** Работа
Пропуск сразу не сработал и решил пропустить меня только с третей попытки. Предъявил на входе банан. Работа внеурочное время так себе. Мой приказ так никто не подписал. С бездельниками надо что-то делать. Серегин пришел ко мне в надежде, что я сегодня не работаю. Ходили толпы бездельников рассказать свою душещипательную историю про новый год.  
*** Семейные ценности
Часть команды расскзал, как сделал предложение своей девушке (с которой 9 лет), Илья - про то, что пора бы и к ней съездить на НГ. Макс - про то, что пора завести детеныша и что у него что-то не получается, Алексей - что он включил перфоратор, Аня - что бухала и бухала. Что-то мне эти разговоры не нравятся.  
*** Чтение
Нашел там книжку с ноута. Уж очень это неудобно. А еще толпы болтающих бездельников. Прочитал только пятую часть. К обеду от бездвиженного сидения уже стало все затекать.  
*** Макадамия
Макс посоветовал орехи. Бербраер их тоже нахвалилва. Купил попробовать. Первый - приольно - новый вкус и приятный запах. После третьего это стало просто неинтересно. Взвесили вес ядрышка к скорлупке и получилось чистая цена 5000 за кило - наркота походу дешевле. Мне не понравилось.  
*** Перехват
Шел с работы. Поболтал с мамой. Смотрю - машина меня дожидается. По номерам что-то знакомое - ну я и сел. Первый раз мы с Димкой пересеклись.  
*** Вибрация
Сходил в магазин, а Димка все еще на парковке с открытым багажником и счастливым (катарсис) лицом. Оторвана панель у багажника и там проводок, который скорее всего трется. Он нашел эту сволочь. Счастливый перетянул все паралонками. Теперь осталось проверить.  
*** Тыква раздора
Приготовил овощное рагу и кинул туда тыкву. Димка стал мрачнее тучи. Ну да, что-то не очень прикольный рецепт.  
** 05.01.2021 Вт
*** Обыденность
И пришла на работу. Антон пришел на работу. Опять эти их семейные ссоры. Прям градус интереса к ней сразу поубавился. Все уже было.  
*** Ветер перемен
Второй раз проскочил слух, что Кн смещают и Ч бедет за него. От этого у меня прям прошла досада от бессилия что-то делать. Все наработки коту под хвост. Надо с этим что-то делать.  
*** Календарик
Запилил И календарик с зубренком. Но мне не нравится на сегодняшний день верстка. Надо что-то думать друге. Вышел распечатать, И разговаривала по телефону у принтера, попросил ее подождать и болтали пока печатается, что-то проскочила боль в груби, было бы не очень красиво грохнуться в такой красивый момент.
*** Финвиз
Скачал нормальные .csv финтрат. Данные гораздо интереснее, но не полные. А еще посмотрел в ЛК траты по дням и офигел слегка. В день по 500-1500. Всего за 2020 250кр затратных. 
*** Преподство
Что-то на волне вчерашних разговоров про семейственность у меня все чаще проявляется непреодолимое желание кого-то учить и властвовать безраздельно. Сегодня посмотрел еще Дугина и это просто прикольно - под старость надо переходить в преподство. Чувак шарит и еще и в теме. Аж подписался на него в ВК.  
** 06.01.2021 Ср
*** Головомойка
Устроили головомойку Ане, сколько желчи и неприязни вызывает эта девочка.  
*** День живота
До этого брал с собой в обед бананы. Сейчас взял картошечку с красной рыбкой. Потом дома набился живот. 
*** Слухи
Озвучил слух по поводу кадровых перестоновок и прям за 15 минут волна женской слуховой сети развеяла слух переведя его в раздел слухов.  
*** Сериальчик
Наткнулся на старинный британский сериал, за вечер осилил 2 сезона. Закончил смотреть в час ночи. Нихрена не выспался. Но сериальчик прикольный.  
*** Чтиво
Дочитал Волмарт. Полнейшая хрень. Хотел поискать что-то еще в чтиво, но сериальчик пересилил меня.  
*** Пенопласт
Димка решил, что звук в комнате проводит дверь. Накрутил на нее пенопласт и думает, что это сработало.  
*** Пароль
Пол дня И и Антон шептались. Решил присоединится к ним. Там просто светские разговоры. Но уровень их общения похож на старую семейную пару. Этот выпендреж Антона и усипуси И. И знает его пароль в телефоне (0356) и они пользуются общими ресурсами. Вместе делят еду. Вместе куда-то гуляют на долго. Меня это бесит.  
*** 50 мм
Смотрел старые семейные фотографии, снятой еще на "смену" (40мм) и прям совершенно необычный эффект всего близкого. Все крупно и детально. Надо быстрее покупать полтинник и пробовать что-то творить
** 07.01.2021 Чт
*** Мойка
Поехали домой. Дорога отвратительная. Димка решил помыть машину. Пол дороги брехал и заставлял меня найти в неработающем интернете, есть ли в Волове мойка. Такой чистой машина не была с конвеера.  
*** Головняк
Что-то меня вырубило после дороги и теперь болит голова.
*** Белое
Такой красивый иней. Рабица и деревья. Все вокруг.
** 08.01.2021 Пт
*** Когнитивное невосприятие
Смотрели "Экспансию" и прям несоответствие брасаются в глаза и теранят мой мозг. В книге более сильные сюжетные повороты и совершенно иные персонажи. В сериале все топорненько подогнано для туповытых зрителей и сокращенное время повествования.  
*** Головняк
Болит голова весь день. Мама сказала, что у нее тоже - у меня прям сразу отпустило.  
** 09.01.2021 Сб
*** Сериальчики
Целый день гоняли сериальчики. То один, то другой. Что-то такое себе времяпрепровождение. За эти 10 дней практически потратил весь 11 ГБ трафик в интернете, впервые за все время пользования телефоном.  
*** Холодная оттепель
Весь день ждали -30оС, а на улице лишь капало с крышь и слоился туман.  
** 10.01.2021 Вс
*** Тула
Поехали в Тулу. Вся машина обледенела коркой. Дворники не работают как надо и всю дорогу я смотрел на мутное пятно перед собой и белый горизонт в боковом. В Туле вообще грязища. 
*** Кино
Посмотрел "Неадекватные люди 2" и прям норм. Первый поинтереснее, а тут девка сама дура. А психолог героически всех спас, хоть и не так как мог. Задуматься заставляет.  
** 11.01.2021 Пн
*** Бездник
Илья проставился за ДР. Поели пирожек. Очень по семейному. Там на верху только и разговоров, что о COVID. Тортики вкусные, но никакого ощущения праздника.  
*** Свободное дыхание
Забыл натянуть маску по привычке и прошелся пару метров по открытому воздуху и такое блаженство и легкость дыхания. Где-то нас притисняют.  
*** Сопровод
Кинул Ане бумаги для работы в почте, дополнил их сопроводительным текстом. Она устроила истерику, что я не могу ей сказать голосом, что я от нее хочу. Истеричка хренова.  
*** Карантин
Пришел ака с карантина. В очереди на вход стоял до 11. Потом были бесконечные разговоры о ковидле. Разжирел на своем больничном. Почему-то все хвалятся, что 10 дней жрали элитное поило.  
*** Олени
Филип пришел в прикольной рубашке с оленями. Потом была плаксивая история про расстование.  
*** Ручка
Ручка двери работает все хуже и хуже. Прибегнул к последнему средству и попросил помощи у Димы. Я даже не заметил, как он пришел и все заработало. Мастер.  
*** Киноклуб
И рассказала, что ей понравились все рекомендации, что я ей давал. Сам попросил совета у Ильи в незнакомой для меня облости аниме. Может и нормальная тема кинофила.  
** 12.01.2021 Вт
*** Киберпанк
Дети с этими светоотражающими вставками в одежде создают унылому ночному городскому окружению немного киберпанковости. Очень эффектно
*** Пробка
Сегодня пробка оказалась еще длиннее и все парковочные места были заняты. Нам это не понравилось.
*** Отчеты
Что-то опять посыпалось как их ведра. Нихрена не готово, несмотря на подготовку за три масяца. Все сначала. Может перемены и к лучшему, хотя Ч не тот человек, который ведется на всю эту чепуху.
*** Сериальчик
Посушил мозг над Вустером. Милый забавный сериальчик и много естестенных костюмов. Но чудеса меня удручают там.
** 13.01.2021 Ср
*** Автоматизация
Мне бы сейчас очень пригодилась. Одно дело - создать БД, другое - заставить ее работать. Опять эти тонны перелопачивания одинаковых данных. Возлагаю надежды на нормальное программирование и интерфейсы. 
*** Черновики
Решил немного навести порядок. 7 пачек израсходованной бумаги. Полдня перекладывал эти бумажки. Ничего полезного. Надо с обновкой руководства обновить и программу экономии бумаги. 
*** Вики
У Мазая возникают странные вопросы про вики, впарил ему, что когда-нибудь это заработает. И еще немногр Жиры в положительном контексте.
*** Морозец
Кончики пальцев замерзли, я сильно задумался, что в детстве небыло такого понимания своего тела. Сейчас я принимаю сигналы и адекватно интерпретирую их. Моя обеденная прогулка по большей части была с замерзшими руками, но буквально за 15 минут до отхода на базу возникла точка перелома и стало тепло, можно было продолжить гулять до бесконечности.  
*** Утка
Готовил сегодня утку, гемора слишком много, удовольствия мало. В мультиварку она не влазела и пришлось сломать ей спину. Кожа жирная и перья торчат пеньками. Замориновать ее не удалось и пришлось делать так. Этот неприятный запах. Гусиное мясо гораздо вкуснее. Тут мясо сухое и жесткое. Никогда больше не покупать утку.  
*** Горелка
Насмотревшись повора, решил купить горелку. В магазине продовец нихрена не понимал и призрительно общался со мной. Не ходить больше в тот магазин. Попробовал жарить лук - не понравилось, вся концепция не понравилась. Эргономика отсутствует, вкусовых качеств не добавляет. Опасный предмет на кухне. Все так себе.  
*** Хлебцы
Нашел в магазине замену сухарей для Димки. Какие-то диетические хлебцы. Я не понял прикола, но Димка говорит, что эти даже лучше, чем дома. Ну и пускай ест их. Я продолжу питаться нормальными добротными сухарями.  
*** Прививочник
Димке сделали прививку от столбняка и он весь вечер жаловался, что у него болит под лопаткой. Почему мне не деалили их никогда, я не знаю.  
*** Ремешок
Забрал с почты ремешок. Резина жесче и есть зазор при монтаже. Нет всех этих предупреждений. Оригенальный был интереснее. У часов все равно уже дохнет акб. Но так (с неиспорченым ремешком) гораждо приятнее, да и разъем питания теперь защелкивается как влитой.  
*** Пурга
Погода разыгралась не на шутку. Местами запорошило всю дорогу. Залипали в окно минут пятнадцать как там "буря мглою небо кроет". Давно не было такой ненастной погоды.  
** 14.01.2021 Чт
*** Запаренный
Кн вызвал меня вечером, когда я уже собрался уходить. Поныл на свою сложную жизнь. Я сообщил что "все фигня - прорвемся" и со спокойной душел пошел домой.  
*** Метафизика
Дугин против Переслегина. У одного мощная филосовская школа с знанием греческого и всех философов лично, у другого достраивание схем и новые смыслы. Я больше за Переслегинский вариант (надо найти книги по схемотизации). И тот и другой обогащают друг друга. Я же не понимаю и половины того, что они говорят.  
*** Пустые бабские разговоры
90% разговоров - полная фигня. Меня сильно раздражает близкие контакты И и Антона, но как показывает мой жизненный опыт - все это фигня и просто люди от безделия ищут общения, или я ничего не понимаю в жизни и так на пустых разговорах люди ездят по ушам и трахаются и потом страдают и это нормальная хреновая жизнь.  
*** Бритва Оккама
Приказ и сложные теории. Не подписывают приказ. Уже стали возникать теории, что это заговор. Потом прилетела доп.информация, что делопроизводитель заболела. Это рушит все сложные теории. Потом делопроизводитель сказала, что приказы не подписывают с 29 числа по непонятным причинам. Незнание порождает ненонимание и стресс. Люди сами накруживают себя. Так и с моей ревностью к И - Пустая ревность. 
*** Ютуб и пустота
Ничего интересного. Убитый вечер. 3х. И так все чаще. Это психологическое дрочево. Безрезультатная безцельная псевдодеятельность.  
** 15.01.2021 Пт
*** Отчеты
Охерели там со своими отчетами, только автоматизация нас спасет. Не успеваю охреневать от закидывания меня заявками на составление отчетов. И так уже несколько лет подряд и никакого профита.  
*** Кельберер 
Была придумана новая единица производительности труда - один кельберер - витрувианский инженер, средневзвешенный ведущий инженер. 
*** Интриган
Все у меня сегодня спрашивают, работаю ли я завтра - да.
*** Группы
Прям прошелся по своим группам, накидал пару интересных ссылок. Почувстовал жажду деятельности. Еще не все потеряно.  
** 16.01.2021 Сб
*** Работа
Работать в субботу - это полная фигня. Пол дня провозился с подготовкой данных. Существенно продвинулся, но морального удовлетворения не получил. Опять все занимаются своими делами. Надо на работе устраивать трахательные комнаты, что бы люди не отвлекались на работу и занимались своими делами.  
*** Комп
Пришел СС и попросил помочь с приказами. Я помог ему с вторым монитором и получил от этого кучу морального удовольствия. Работа со всем этим старым железом, улучшение эрогономики рабочего места, настройки и понимание того, что до меня это никто не сделал.  
*** Пенаты
Поехали в магазин за незамерзайкой. Дорога отрвратительная. Мазагин безлюдный, консультанты аж драться чуть не кинулись за нас от скуки. Ассортимент побольше, чем в Леруа. Толчки подвесные есть красивые. А вот раковины (точнее подраковенные тумбочки) мне не понравились. Магазин странный. Вообще не понимаю идею этих магазинов.  
*** Пурга
Погода отвратительная. Дорога вся занесена. Решили, что правильно поступили, что не поехали домой. Дорога скользкая и вообще лучше никуда не выходить. Мело весь остаток дня.  
*** Магазин
ДК перекрыт полностью, в соседних магазинах нет ничего приличного. Как-то грустно стало без привычных магазинчиков. Это активная политическая борьба с неугодными конкурентами.  
*** Карточка
Треснула антенка и карточка не работает как должна. Добрая женщина в магазине предложила вставить ее чипом и это помогло. До конца действия не дотянула пару месяцев. Не буду ее перевыпускать сам, пускай все идет своим чередом. Перейду на Мастре. Надо купить обложку для нее. 
** 17.01.2021 Вс
*** Велосипедисты
Наблюдал в окно велосипедиста. На улице -19оС. Это конечно не от хорошей жизни, но популяризация велосипедов меня больше радует, чем удручает. Но зимой кататься я не хочу.  
*** Отказоустойчивость
Надо придумывать такую систему снабжения, защищенную от отказа узловой точки. В окрестностях это более менее реализовано. Надо в квартиропоиске учесть и такой коэффициент, как устойчивость инфраструктуры (по магазинам, воде, электричеству). В соседнем супермаркетет все на взводе, покупатели на взводе (если закроют еще и этот - придется бегать по всему району и отказаться от привычных продуктов). Нашел орехи подешевле в полатке поближе, еще бы они поставили себе терминал.  
*** Разборки
Разобрался немного в делах. Но опять не успел сделать ничего. Этот ютуб отнимает чрезвычайно много времени. Хотя накопировал себе книг - читать не перечитать.  
*** Инстарис
Запилил прикольную гарбушу с рисом. Получилось замечательно. Аж решил сфотать ее в свою группу.  
*** Телевизор
Дома кончился телевизор. Надо бы не продлевать его, но что-то они там грустят без телека.   
*** Интернет
В магазинах нет ничего приличного. А в интернете уже гораздо проще купить всю эту мелочевку. Надо потренироваться в интернетмагазине. 
*** Программирование
Нашел прикольный канал с программированием - надо практиковаться. 
*** Серая зона
Знаешь человека много лет, а в интернете он совсем другой. И тут суровый мужик лайкает тортики, а циничная женщина - котиков, а мамы красивейшие картинки - никому нельзя верить, все надо парсить и анализировать, собирать собьективные субьективные сведения и проводить тестирование гипотез
** 18.01.2021 Пн
*** Делай добро и убегай
Наконец подписали приказ и я подкинул И ее экземпляр. Она поблагодарила меня конфеткой. Вот уж действительно "делай добро и убегай". Что за несправедливая жизнь.  
*** Наконец пришла зима.
Холодает. -21оС. Решил не идти домой пешком и дождался Димку (хотя можно было и прогуляться). Простоял дожидаясь его и еще стояли в пробке. Потом пошел в магаз по холодному воздуху. Так себе ощущуния
*** Чеклист
Подбил работы в табличку. Кн забрал ее себе. На следующий день подбил табличку на вики, Кн не оценил всей прелести (потомучто смотрит не в том браузере). Но мне табличка понравилась. Очень полезная.  
** 19.01.2021 Вт
*** Работун
Сделал сегодня вал работ, узнал что делаю дублированную работу, охреневаю от бездельников. И у меня возникают мысли работать с ними? Всех разогнать, кто не хочет работать.  
*** Сплетница
Появился в наших рядах сплетник, человек потерял всякое уважение в моих глазах. Всю дорогу до дома думал, как его уязвить так посмачнее. Когда пересекся с ним на следующий день, даже не обратил внимания, что он есть в комнате. Все эти бессмысленные обдумывания вариантов только вредят полноценному сну.  
*** Ошибки
Просил же проверить, эти бездельники бесполезны. Теперь исправлять ошибки. Забыл кавычки и теперь бумага выглядит как несуразица.  
*** Кельберер
Узнал, что производительность труда меряют в (рублей в час) (прибыли) и это очевидно просто. Ставим это в числитель, а интенсивность в знаменатель расходы (ЗП и накладные). Надо еще раз поштудировать старика Маркса.
*** Столовка
Открылся наконец малый зал, это божественнш, чистые ложки, теплая еда, приятрые люди, камерная обстановка
** 20.01.2021 Ср
*** Оперативное управление
Раскрасил табличку того, что надо сделать. Табличка в красном. Сделано почти нихрена. Кругом одни бездельники. 
*** Быка за рога
Когда вчера уходил, помохал в след уходящей И. Она пригрозила начать ко мне приставать, но утром, прямо с порога стала приставать скаким-то 1с. Утренний ликбез 1С привел меня к мысли, а не поучиться этому дрянному продукту. Общение с пятнашечниками оставило у меня только возглас "ебнутая пизда" для женщины которая позвонила по моему запросу на консультацию и сказала, что у нее нет сейчас времени.  
*** Прогулка
Безмашинное производство
*** Картошечка
Очень вкусная жаренная кортошечка. Давно о ней мечтал. А немного остывшая она просто бесподобна.  
*** 90 дней
ДК открылся обратно. Это прям облегчение от моей бананово сухарной ломки
*** Полуночник
Димка вернулся под вечер, когда я уже собирался спать
** 21.01.2021 Чт
*** Снежная борода
Поземка и мороз. Погода вообще странная. Негулябельно. Все дорожки занесло. 
*** Мотивация
Считалочка и сопротивление. Сделал ексель модель распределения премиального фонда. Получилось очень красиво и наглядно. Никто не в состоянии оценить ее прелесть. Пытался у Мотивационшиков спросить как это работат - они не знают. Марат обращался ко мне на Вы, другие просто узкие. 
*** Контраргумертация
Поти кинул мне работу, я чет вспылил и пошел козырями. Адреналил хлестал через край. День испорчен.  
*** Киндзадза
Большова встретилась в коридоре и предъявила на мое старое замечание про возможности почты. Она походу туповата. 
*** Лориенс Аравийский
Ты кто такой? Такой вопрос я услышал от Фили. Потом Кн спросил как нам от него избавиться)) И чтоб Мелю забирал (всех пришлых (а я еще бы сдал Поню))
*** Переработки
Пока обьяснишь все этим начальникам, уже переработал час. Конечно никто мне за него не заплатит. 
*** Ты проджект менеджер
В действиьельности все не так как на самом деле. Встретил Лешу, он рассказывал, что ровно было на бумаге.  
** 22.01.2021 Пт
*** Тепло
На улице оттепель, все тает. На фоне позувчерашних -20оС этот перепад просто невообразим. Дороги раскисли и проходимость срезко уменьшилась. Машины вязнут в снежной каше и шлифуют асфальт. Димка каждый раз пытается кинуть машину в занос и сегодня это получилось особенно сильно. 
*** Закрывушка
Успел сделать свою часть работы во время. Потом выяснилось, что с ошибками :) А руководство не справилось со своей работой. Предявил Филе, что он хреново работает, тот развопился, я ответил ему. Предъявил это Кн. Он схватился за голову и сказал, как бы убрать этих понаехавших. Ахаха. Моя пропаганда "всех уволить" приносит свои плоды. 
*** Неудобные вопросы
Накрутил вопросы про будущее - решил оставть их на послеаттестации, задал вопросы про адекватность - нет, было мне в ответ. Все вопросы, которые я задаю, вязнут в Лете. Бессмысленный диалог. 
*** Искры
Трамвайчик и столб искр. Возвращался из магазина, по раскисшим рельсам трамвая проехался этот самый трамвай. За ним на сварке рельсов столб искр и сердце убегает у меня в пятки. Димка сказал, что там всего 27 вольт (боюсь предположить, сколько там ампер). Очень странный транспорт.  
*** Лапочка
Пришел (точнее привела Мария) ко мне Лапочка, узнать, что делать с сетевым диском. Я решил прогнать на нем тест на профпригодность. И он его прошел. Есть еще вера в человечество. Потом эти имбицилы предъявляли, что я шлепнул визу на подотчетном мне документе. А Лапочка превратился в Евгения Владимировича. 
*** Пожарный
Нашел интересный канал про программирование на ВБА от пожарного. Сижу залипаю. Не думал, что "силовики" склонные к риску, могут так мастерски управляться простейшими пользовательскими инструментами, в то время как инженеры в ведущей компании пользуются компьютером, как печатной машинкой.  
*** Трикстер
Антон соблазняет меня переехать в лучшую половину комнаты. У меня зародились такие-же мысли. Только в болото.  
** 23.01.2021 Сб
*** Работа
Понесло меня на работу. Целый день убил на 5 из 25 табличек. Уже глаза на лоб лезут от этого всего. 
*** Пропаганда
Показал Игорю считалочку премий. Начал втирать ему про идеальное планирование. Заинтриговал ака, но ничего ему не показал. Если мои подсчеты верны, премия должна быть как вторая зарплата. Почему у меня за все время работы было только 2 таких выплаты, и они ни в одном месте не были похожи на вторую зарплату.  
*** Дождь
За окном идет дождь. Снежная каша на дороге превратилась в снежный суп. Вся трасса сырая и машины едут на облаках. От фур шлейф тянется на сотню метров. Зато машина не заляпана, а практически белая. 
*** Дом
Вместо того, чтобы чистить снег на придворовой территории для машины, мама просто утоптала всю площадку. Так получилось даже лучше. Снег дольше не растает. Нет этих гор отвала. Машина на маленькой подиуме. Дома хорошо. Выйдешь в сад, а там сад. Нужно минимум 8 соток пространства. Как же хорошо иметь частный дом. 
** 24.01.2021 Вс
*** Маленький принц
Утром проснулся раньше все и не смог быстро заснуть. Решил почитать. Достал Маленького принца и это просто офигительно. 
*** Туман
 
*** Женщина с машиной

