* Jan
** 01.01.2021 Пт
*** Ледяные цветы
Абсолютно все зашито в ледяно понцирь. Туман осаждает на деревьях и цветах иней и они превращаются в ледяные цветы. Каждый раз выходя из дома попадаешь в зимнюю сказку.  
*** Сериальчики
Занимали день сегодня безудержным просмотром сериалов. Один безинтереснее другого. В это время каждый занимался своим делом. Мама разгадывала сканворды, Димка играл в Факторио, я читал книжку. Папа спал.  
*** Реклама
От безделья понесло меня в Ютуб на телефоне. О ужас. Я узрел рекламу. Это отвратительная мерзость. Как люди вообще сидят не в Опере. Блаженные в своем неведении люди смотрят ютуб с этой рекламой. Я то думал, что мерзость, это когда ведущие непосредственно рекламят свякие игрушки и голосом рассказывают как они там что-то делают, но это было лишь вершиной айсберга. Ютуб сам суют каждые 5 минут левую рекламу - это ужасно. Жду недождусь, когда вернусь к просмотру ютубчика в Опере.  
*** План А
Начал читать "Республика Волмарт" и это вызвало у меня прямые асоциации для лого одной из моих групп. По приезду к нормальному компу надо будет перерисовать в нормальных скруглениямх и цеветах. Но пока пятилучевая звездочка (мир без звездочек) и градиент перехода (как в загрузке (только я ошибся и нарисовал градиент в другую сторону). Символизируют загрузку новой SocOS.  
** 02.01.2021 Сб
*** Отвертка
Просятил Димук, что в Никоновских объективах морочкик в фотике и крутится там отвертка. Почему они такие дорогие, мы не придумали.  
*** Снежки
Димка пошел приклеивать градусник и зарядил снежки в рабицу. Получились прикольные дыры в ледяном панцире сетки. Выглядело более чем эффектно.  
*** Чтиво
Практически весь день придавался чтению Волмарта. Не Стивенсон конечно, но годнота.  
*** Сериальчик
Посмотрели Звездный путь. Кругом сплошная политкоректота, но с фантастической точки зрения никакой.  
** 03.01.2021 Вс
*** Арома
Обновил еще один балон масляной мяты, разлил балон спиртовой мяты и балон дегтя. Может показаться странным, но это работает (пока не доказано обратное).  
*** Горизонт
Когда поехали, были прикольные виды с снежными тучами и самосветящимся горизонтом. Четкое разделение неба и земли застовило задуматься "как давно я вообще видел горизонт". Деревья в ледяных панцирях и грязная дорога.  
*** Непрядва
Заехали за Катей. Там бабская суета и Леша жарит шашлык. Катя набрала тяжеленную сумку. Степка уже указывает, что надо закрыть дверь. Все хорошо. Мама просила сфотать речку.  
*** Тула
Приехали. Тут грязища. Скука скучная и единстенное развлечение - компьютер. Надо переводить этот инструмент из разряда развлечений в дело.  
*** Дугин
Это прекрасно. Посмотрел НГ обращение Дугина на Авроре и просто катался по полу от смеха. Один из немногих русских философов современности цитирует мемасики и призывает читать классиков. Он шикарен.  
** 04.01.2021 Пн
*** Отпросилась
Погда я еще спал, но уже успел заварить чаек и залезть в ВК, мне написала И, и сообщила, что не придет сегодня, и ей слишком лениво. Я что-то прям расстроился и решил пойти в спортивной одежде и вообще отмести любые приличия и деградировать. Я удручен.  
*** Работа
Пропуск сразу не сработал и решил пропустить меня только с третей попытки. Предъявил на входе банан. Работа внеурочное время так себе. Мой приказ так никто не подписал. С бездельниками надо что-то делать. Серегин пришел ко мне в надежде, что я сегодня не работаю. Ходили толпы бездельников рассказать свою душещипательную историю про новый год.  
*** Семейные ценности
Часть команды расскзал, как сделал предложение своей девушке (с которой 9 лет), Илья - про то, что пора бы и к ней съездить на НГ. Макс - про то, что пора завести детеныша и что у него что-то не получается, Алексей - что он включил перфоратор, Аня - что бухала и бухала. Что-то мне эти разговоры не нравятся.  
*** Чтение
Нашел там книжку с ноута. Уж очень это неудобно. А еще толпы болтающих бездельников. Прочитал только пятую часть. К обеду от бездвиженного сидения уже стало все затекать.  
*** Макадамия
Макс посоветовал орехи. Бербраер их тоже нахвалилва. Купил попробовать. Первый - приольно - новый вкус и приятный запах. После третьего это стало просто неинтересно. Взвесили вес ядрышка к скорлупке и получилось чистая цена 5000 за кило - наркота походу дешевле. Мне не понравилось.  
*** Перехват
Шел с работы. Поболтал с мамой. Смотрю - машина меня дожидается. По номерам что-то знакомое - ну я и сел. Первый раз мы с Димкой пересеклись.  
*** Вибрация
Сходил в магазин, а Димка все еще на парковке с открытым багажником и счастливым (катарсис) лицом. Оторвана панель у багажника и там проводок, который скорее всего трется. Он нашел эту сволочь. Счастливый перетянул все паралонками. Теперь осталось проверить.  
*** Тыква раздора
Приготовил овощное рагу и кинул туда тыкву. Димка стал мрачнее тучи. Ну да, что-то не очень прикольный рецепт.  
** 05.01.2021 Вт
*** Обыденность
И пришла на работу. Антон пришел на работу. Опять эти их семейные ссоры. Прям градус интереса к ней сразу поубавился. Все уже было.  
*** Ветер перемен
Второй раз проскочил слух, что Кн смещают и Ч бедет за него. От этого у меня прям прошла досада от бессилия что-то делать. Все наработки коту под хвост. Надо с этим что-то делать.  
*** Календарик
Запилил И календарик с зубренком. Но мне не нравится на сегодняшний день верстка. Надо что-то думать друге. Вышел распечатать, И разговаривала по телефону у принтера, попросил ее подождать и болтали пока печатается, что-то проскочила боль в груби, было бы не очень красиво грохнуться в такой красивый момент.
*** Финвиз
Скачал нормальные .csv финтрат. Данные гораздо интереснее, но не полные. А еще посмотрел в ЛК траты по дням и офигел слегка. В день по 500-1500. Всего за 2020 250кр затратных. 
*** Преподство
Что-то на волне вчерашних разговоров про семейственность у меня все чаще проявляется непреодолимое желание кого-то учить и властвовать безраздельно. Сегодня посмотрел еще Дугина и это просто прикольно - под старость надо переходить в преподство. Чувак шарит и еще и в теме. Аж подписался на него в ВК.  
** 06.01.2021 Ср
*** Головомойка
Устроили головомойку Ане, сколько желчи и неприязни вызывает эта девочка.  
*** День живота
До этого брал с собой в обед бананы. Сейчас взял картошечку с красной рыбкой. Потом дома набился живот. 
*** Слухи
Озвучил слух по поводу кадровых перестоновок и прям за 15 минут волна женской слуховой сети развеяла слух переведя его в раздел слухов.  
*** Сериальчик
Наткнулся на старинный британский сериал, за вечер осилил 2 сезона. Закончил смотреть в час ночи. Нихрена не выспался. Но сериальчик прикольный.  
*** Чтиво
Дочитал Волмарт. Полнейшая хрень. Хотел поискать что-то еще в чтиво, но сериальчик пересилил меня.  
*** Пенопласт
Димка решил, что звук в комнате проводит дверь. Накрутил на нее пенопласт и думает, что это сработало.  
*** Пароль
Пол дня И и Антон шептались. Решил присоединится к ним. Там просто светские разговоры. Но уровень их общения похож на старую семейную пару. Этот выпендреж Антона и усипуси И. И знает его пароль в телефоне (0356) и они пользуются общими ресурсами. Вместе делят еду. Вместе куда-то гуляют на долго. Меня это бесит.  
*** 50 мм
Смотрел старые семейные фотографии, снятой еще на "смену" (40мм) и прям совершенно необычный эффект всего близкого. Все крупно и детально. Надо быстрее покупать полтинник и пробовать что-то творить
** 07.01.2021 Чт
*** Мойка
Поехали домой. Дорога отвратительная. Димка решил помыть машину. Пол дороги брехал и заставлял меня найти в неработающем интернете, есть ли в Волове мойка. Такой чистой машина не была с конвеера.  
*** Головняк
Что-то меня вырубило после дороги и теперь болит голова.
*** Белое
Такой красивый иней. Рабица и деревья. Все вокруг.
** 08.01.2021 Пт
*** Когнитивное невосприятие
Смотрели "Экспансию" и прям несоответствие брасаются в глаза и теранят мой мозг. В книге более сильные сюжетные повороты и совершенно иные персонажи. В сериале все топорненько подогнано для туповытых зрителей и сокращенное время повествования.  
*** Головняк
Болит голова весь день. Мама сказала, что у нее тоже - у меня прям сразу отпустило.  
** 09.01.2021 Сб
*** Сериальчики
Целый день гоняли сериальчики. То один, то другой. Что-то такое себе времяпрепровождение. За эти 10 дней практически потратил весь 11 ГБ трафик в интернете, впервые за все время пользования телефоном.  
*** Холодная оттепель
Весь день ждали -30оС, а на улице лишь капало с крышь и слоился туман.  
** 10.01.2021 Вс
*** Тула
Поехали в Тулу. Вся машина обледенела коркой. Дворники не работают как надо и всю дорогу я смотрел на мутное пятно перед собой и белый горизонт в боковом. В Туле вообще грязища. 
*** Кино
Посмотрел "Неадекватные люди 2" и прям норм. Первый поинтереснее, а тут девка сама дура. А психолог героически всех спас, хоть и не так как мог. Задуматься заставляет.  
** 11.01.2021 Пн
*** Бездник
Илья проставился за ДР. Поели пирожек. Очень по семейному. Там на верху только и разговоров, что о COVID. Тортики вкусные, но никакого ощущения праздника.  
*** Свободное дыхание
Забыл натянуть маску по привычке и прошелся пару метров по открытому воздуху и такое блаженство и легкость дыхания. Где-то нас притисняют.  
*** Сопровод
Кинул Ане бумаги для работы в почте, дополнил их сопроводительным текстом. Она устроила истерику, что я не могу ей сказать голосом, что я от нее хочу. Истеричка хренова.  
*** Карантин
Пришел ака с карантина. В очереди на вход стоял до 11. Потом были бесконечные разговоры о ковидле. Разжирел на своем больничном. Почему-то все хвалятся, что 10 дней жрали элитное поило.  
*** Олени
Филип пришел в прикольной рубашке с оленями. Потом была плаксивая история про расстование.  
*** Ручка
Ручка двери работает все хуже и хуже. Прибегнул к последнему средству и попросил помощи у Димы. Я даже не заметил, как он пришел и все заработало. Мастер.  
*** Киноклуб
И рассказала, что ей понравились все рекомендации, что я ей давал. Сам попросил совета у Ильи в незнакомой для меня облости аниме. Может и нормальная тема кинофила.  
** 12.01.2021 Вт
*** Киберпанк
Дети с этими светоотражающими вставками в одежде создают унылому ночному городскому окружению немного киберпанковости. Очень эффектно
*** Пробка
Сегодня пробка оказалась еще длиннее и все парковочные места были заняты. Нам это не понравилось.
*** Отчеты
Что-то опять посыпалось как их ведра. Нихрена не готово, несмотря на подготовку за три масяца. Все сначала. Может перемены и к лучшему, хотя Ч не тот человек, который ведется на всю эту чепуху.
*** Сериальчик
Посушил мозг над Вустером. Милый забавный сериальчик и много естестенных костюмов. Но чудеса меня удручают там.
** 13.01.2021 Ср
*** Автоматизация
Мне бы сейчас очень пригодилась. Одно дело - создать БД, другое - заставить ее работать. Опять эти тонны перелопачивания одинаковых данных. Возлагаю надежды на нормальное программирование и интерфейсы. 
*** Черновики
Решил немного навести порядок. 7 пачек израсходованной бумаги. Полдня перекладывал эти бумажки. Ничего полезного. Надо с обновкой руководства обновить и программу экономии бумаги. 
*** Вики
У Мазая возникают странные вопросы про вики, впарил ему, что когда-нибудь это заработает. И еще немногр Жиры в положительном контексте.
*** Морозец
Кончики пальцев замерзли, я сильно задумался, что в детстве небыло такого понимания своего тела. Сейчас я принимаю сигналы и адекватно интерпретирую их. Моя обеденная прогулка по большей части была с замерзшими руками, но буквально за 15 минут до отхода на базу возникла точка перелома и стало тепло, можно было продолжить гулять до бесконечности.  
*** Утка
Готовил сегодня утку, гемора слишком много, удовольствия мало. В мультиварку она не влазела и пришлось сломать ей спину. Кожа жирная и перья торчат пеньками. Замориновать ее не удалось и пришлось делать так. Этот неприятный запах. Гусиное мясо гораздо вкуснее. Тут мясо сухое и жесткое. Никогда больше не покупать утку.  
*** Горелка
Насмотревшись повора, решил купить горелку. В магазине продовец нихрена не понимал и призрительно общался со мной. Не ходить больше в тот магазин. Попробовал жарить лук - не понравилось, вся концепция не понравилась. Эргономика отсутствует, вкусовых качеств не добавляет. Опасный предмет на кухне. Все так себе.  
*** Хлебцы
Нашел в магазине замену сухарей для Димки. Какие-то диетические хлебцы. Я не понял прикола, но Димка говорит, что эти даже лучше, чем дома. Ну и пускай ест их. Я продолжу питаться нормальными добротными сухарями.  
*** Прививочник
Димке сделали прививку от столбняка и он весь вечер жаловался, что у него болит под лопаткой. Почему мне не деалили их никогда, я не знаю.  
*** Ремешок
Забрал с почты ремешок. Резина жесче и есть зазор при монтаже. Нет всех этих предупреждений. Оригенальный был интереснее. У часов все равно уже дохнет акб. Но так (с неиспорченым ремешком) гораждо приятнее, да и разъем питания теперь защелкивается как влитой.  
*** Пурга
Погода разыгралась не на шутку. Местами запорошило всю дорогу. Залипали в окно минут пятнадцать как там "буря мглою небо кроет". Давно не было такой ненастной погоды.  
** 14.01.2021 Чт
*** Запаренный
Кн вызвал меня вечером, когда я уже собрался уходить. Поныл на свою сложную жизнь. Я сообщил что "все фигня - прорвемся" и со спокойной душел пошел домой.  
*** Метафизика
Дугин против Переслегина. У одного мощная филосовская школа с знанием греческого и всех философов лично, у другого достраивание схем и новые смыслы. Я больше за Переслегинский вариант (надо найти книги по схемотизации). И тот и другой обогащают друг друга. Я же не понимаю и половины того, что они говорят.  
*** Пустые бабские разговоры
90% разговоров - полная фигня. Меня сильно раздражает близкие контакты И и Антона, но как показывает мой жизненный опыт - все это фигня и просто люди от безделия ищут общения, или я ничего не понимаю в жизни и так на пустых разговорах люди ездят по ушам и трахаются и потом страдают и это нормальная хреновая жизнь.  
*** Бритва Оккама
Приказ и сложные теории. Не подписывают приказ. Уже стали возникать теории, что это заговор. Потом прилетела доп.информация, что делопроизводитель заболела. Это рушит все сложные теории. Потом делопроизводитель сказала, что приказы не подписывают с 29 числа по непонятным причинам. Незнание порождает ненонимание и стресс. Люди сами накруживают себя. Так и с моей ревностью к И - Пустая ревность. 
*** Ютуб и пустота
Ничего интересного. Убитый вечер. 3х. И так все чаще. Это психологическое дрочево. Безрезультатная безцельная псевдодеятельность.  
** 15.01.2021 Пт
*** Отчеты
Охерели там со своими отчетами, только автоматизация нас спасет. Не успеваю охреневать от закидывания меня заявками на составление отчетов. И так уже несколько лет подряд и никакого профита.  
*** Кельберер 
Была придумана новая единица производительности труда - один кельберер - витрувианский инженер, средневзвешенный ведущий инженер. 
*** Интриган
Все у меня сегодня спрашивают, работаю ли я завтра - да.
*** Группы
Прям прошелся по своим группам, накидал пару интересных ссылок. Почувстовал жажду деятельности. Еще не все потеряно.  
** 16.01.2021 Сб
*** Работа
Работать в субботу - это полная фигня. Пол дня провозился с подготовкой данных. Существенно продвинулся, но морального удовлетворения не получил. Опять все занимаются своими делами. Надо на работе устраивать трахательные комнаты, что бы люди не отвлекались на работу и занимались своими делами.  
*** Комп
Пришел СС и попросил помочь с приказами. Я помог ему с вторым монитором и получил от этого кучу морального удовольствия. Работа со всем этим старым железом, улучшение эрогономики рабочего места, настройки и понимание того, что до меня это никто не сделал.  
*** Пенаты
Поехали в магазин за незамерзайкой. Дорога отрвратительная. Мазагин безлюдный, консультанты аж драться чуть не кинулись за нас от скуки. Ассортимент побольше, чем в Леруа. Толчки подвесные есть красивые. А вот раковины (точнее подраковенные тумбочки) мне не понравились. Магазин странный. Вообще не понимаю идею этих магазинов.  
*** Пурга
Погода отвратительная. Дорога вся занесена. Решили, что правильно поступили, что не поехали домой. Дорога скользкая и вообще лучше никуда не выходить. Мело весь остаток дня.  
*** Магазин
ДК перекрыт полностью, в соседних магазинах нет ничего приличного. Как-то грустно стало без привычных магазинчиков. Это активная политическая борьба с неугодными конкурентами.  
*** Карточка
Треснула антенка и карточка не работает как должна. Добрая женщина в магазине предложила вставить ее чипом и это помогло. До конца действия не дотянула пару месяцев. Не буду ее перевыпускать сам, пускай все идет своим чередом. Перейду на Мастре. Надо купить обложку для нее. 
** 17.01.2021 Вс
*** Велосипедисты
Наблюдал в окно велосипедиста. На улице -19оС. Это конечно не от хорошей жизни, но популяризация велосипедов меня больше радует, чем удручает. Но зимой кататься я не хочу.  
*** Отказоустойчивость
Надо придумывать такую систему снабжения, защищенную от отказа узловой точки. В окрестностях это более менее реализовано. Надо в квартиропоиске учесть и такой коэффициент, как устойчивость инфраструктуры (по магазинам, воде, электричеству). В соседнем супермаркетет все на взводе, покупатели на взводе (если закроют еще и этот - придется бегать по всему району и отказаться от привычных продуктов). Нашел орехи подешевле в полатке поближе, еще бы они поставили себе терминал.  
*** Разборки
Разобрался немного в делах. Но опять не успел сделать ничего. Этот ютуб отнимает чрезвычайно много времени. Хотя накопировал себе книг - читать не перечитать.  
*** Инстарис
Запилил прикольную гарбушу с рисом. Получилось замечательно. Аж решил сфотать ее в свою группу.  
*** Телевизор
Дома кончился телевизор. Надо бы не продлевать его, но что-то они там грустят без телека.   
*** Интернет
В магазинах нет ничего приличного. А в интернете уже гораздо проще купить всю эту мелочевку. Надо потренироваться в интернетмагазине. 
*** Программирование
Нашел прикольный канал с программированием - надо практиковаться. 
*** Серая зона
Знаешь человека много лет, а в интернете он совсем другой. И тут суровый мужик лайкает тортики, а циничная женщина - котиков, а мамы красивейшие картинки - никому нельзя верить, все надо парсить и анализировать, собирать собьективные субьективные сведения и проводить тестирование гипотез
** 18.01.2021 Пн
*** Делай добро и убегай
Наконец подписали приказ и я подкинул И ее экземпляр. Она поблагодарила меня конфеткой. Вот уж действительно "делай добро и убегай". Что за несправедливая жизнь.  
*** Наконец пришла зима.
Холодает. -21оС. Решил не идти домой пешком и дождался Димку (хотя можно было и прогуляться). Простоял дожидаясь его и еще стояли в пробке. Потом пошел в магаз по холодному воздуху. Так себе ощущуния
*** Чеклист
Подбил работы в табличку. Кн забрал ее себе. На следующий день подбил табличку на вики, Кн не оценил всей прелести (потомучто смотрит не в том браузере). Но мне табличка понравилась. Очень полезная.  
** 19.01.2021 Вт
*** Работун
Сделал сегодня вал работ, узнал что делаю дублированную работу, охреневаю от бездельников. И у меня возникают мысли работать с ними? Всех разогнать, кто не хочет работать.  
*** Сплетница
Появился в наших рядах сплетник, человек потерял всякое уважение в моих глазах. Всю дорогу до дома думал, как его уязвить так посмачнее. Когда пересекся с ним на следующий день, даже не обратил внимания, что он есть в комнате. Все эти бессмысленные обдумывания вариантов только вредят полноценному сну.  
*** Ошибки
Просил же проверить, эти бездельники бесполезны. Теперь исправлять ошибки. Забыл кавычки и теперь бумага выглядит как несуразица.  
*** Кельберер
Узнал, что производительность труда меряют в (рублей в час) (прибыли) и это очевидно просто. Ставим это в числитель, а интенсивность в знаменатель расходы (ЗП и накладные). Надо еще раз поштудировать старика Маркса.
*** Столовка
Открылся наконец малый зал, это божественнш, чистые ложки, теплая еда, приятрые люди, камерная обстановка
** 20.01.2021 Ср
*** Оперативное управление
Раскрасил табличку того, что надо сделать. Табличка в красном. Сделано почти нихрена. Кругом одни бездельники. 
*** Быка за рога
Когда вчера уходил, помохал в след уходящей И. Она пригрозила начать ко мне приставать, но утром, прямо с порога стала приставать скаким-то 1с. Утренний ликбез 1С привел меня к мысли, а не поучиться этому дрянному продукту. Общение с пятнашечниками оставило у меня только возглас "ебнутая пизда" для женщины которая позвонила по моему запросу на консультацию и сказала, что у нее нет сейчас времени.  
*** Прогулка
Безмашинное производство
*** Картошечка
Очень вкусная жаренная кортошечка. Давно о ней мечтал. А немного остывшая она просто бесподобна.  
*** 90 дней
ДК открылся обратно. Это прям облегчение от моей бананово сухарной ломки
*** Полуночник
Димка вернулся под вечер, когда я уже собирался спать
** 21.01.2021 Чт
*** Снежная борода
Поземка и мороз. Погода вообще странная. Негулябельно. Все дорожки занесло. 
*** Мотивация
Считалочка и сопротивление. Сделал ексель модель распределения премиального фонда. Получилось очень красиво и наглядно. Никто не в состоянии оценить ее прелесть. Пытался у Мотивационшиков спросить как это работат - они не знают. Марат обращался ко мне на Вы, другие просто узкие. 
*** Контраргумертация
Поти кинул мне работу, я чет вспылил и пошел козырями. Адреналил хлестал через край. День испорчен.  
*** Киндзадза
Большова встретилась в коридоре и предъявила на мое старое замечание про возможности почты. Она походу туповата. 
*** Лориенс Аравийский
Ты кто такой? Такой вопрос я услышал от Фили. Потом Кн спросил как нам от него избавиться)) И чтоб Мелю забирал (всех пришлых (а я еще бы сдал Поню))
*** Переработки
Пока обьяснишь все этим начальникам, уже переработал час. Конечно никто мне за него не заплатит. 
*** Ты проджект менеджер
В действиьельности все не так как на самом деле. Встретил Лешу, он рассказывал, что ровно было на бумаге.  
** 22.01.2021 Пт
*** Тепло
На улице оттепель, все тает. На фоне позувчерашних -20оС этот перепад просто невообразим. Дороги раскисли и проходимость срезко уменьшилась. Машины вязнут в снежной каше и шлифуют асфальт. Димка каждый раз пытается кинуть машину в занос и сегодня это получилось особенно сильно. 
*** Закрывушка
Успел сделать свою часть работы во время. Потом выяснилось, что с ошибками :) А руководство не справилось со своей работой. Предявил Филе, что он хреново работает, тот развопился, я ответил ему. Предъявил это Кн. Он схватился за голову и сказал, как бы убрать этих понаехавших. Ахаха. Моя пропаганда "всех уволить" приносит свои плоды. 
*** Неудобные вопросы
Накрутил вопросы про будущее - решил оставть их на послеаттестации, задал вопросы про адекватность - нет, было мне в ответ. Все вопросы, которые я задаю, вязнут в Лете. Бессмысленный диалог. 
*** Искры
Трамвайчик и столб искр. Возвращался из магазина, по раскисшим рельсам трамвая проехался этот самый трамвай. За ним на сварке рельсов столб искр и сердце убегает у меня в пятки. Димка сказал, что там всего 27 вольт (боюсь предположить, сколько там ампер). Очень странный транспорт.  
*** Лапочка
Пришел (точнее привела Мария) ко мне Лапочка, узнать, что делать с сетевым диском. Я решил прогнать на нем тест на профпригодность. И он его прошел. Есть еще вера в человечество. Потом эти имбицилы предъявляли, что я шлепнул визу на подотчетном мне документе. А Лапочка превратился в Евгения Владимировича. 
*** Пожарный
Нашел интересный канал про программирование на ВБА от пожарного. Сижу залипаю. Не думал, что "силовики" склонные к риску, могут так мастерски управляться простейшими пользовательскими инструментами, в то время как инженеры в ведущей компании пользуются компьютером, как печатной машинкой.  
*** Трикстер
Антон соблазняет меня переехать в лучшую половину комнаты. У меня зародились такие-же мысли. Только в болото.  
** 23.01.2021 Сб
*** Работа
Понесло меня на работу. Целый день убил на 5 из 25 табличек. Уже глаза на лоб лезут от этого всего. 
*** Пропаганда
Показал Игорю считалочку премий. Начал втирать ему про идеальное планирование. Заинтриговал ака, но ничего ему не показал. Если мои подсчеты верны, премия должна быть как вторая зарплата. Почему у меня за все время работы было только 2 таких выплаты, и они ни в одном месте не были похожи на вторую зарплату.  
*** Дождь
За окном идет дождь. Снежная каша на дороге превратилась в снежный суп. Вся трасса сырая и машины едут на облаках. От фур шлейф тянется на сотню метров. Зато машина не заляпана, а практически белая. 
*** Дом
Вместо того, чтобы чистить снег на придворовой территории для машины, мама просто утоптала всю площадку. Так получилось даже лучше. Снег дольше не растает. Нет этих гор отвала. Машина на маленькой подиуме. Дома хорошо. Выйдешь в сад, а там сад. Нужно минимум 8 соток пространства. Как же хорошо иметь частный дом. 
** 24.01.2021 Вс
*** Маленький принц
Утром проснулся раньше все и не смог быстро заснуть. Решил почитать. Достал Маленького принца и это просто офигительно. 
*** Туман
Не видно ни зги. Выехали немного попозже, думая, что туман рассеится. В районе он был метров 50, дальне немного рассеялся. По трассе машины летят, как срасть хотят. Сделал фотку где нет горизонта и нет дороги вперед. Вокруг вообще нет ничего, только лошадке хорошо.  
*** Женщина с машиной
При въезде в Тулу опять эта женщита стоит там уже 2 недели с открытым капотом. Подозрительно. Ржали долго.  
*** USB
Поставил ОС на 3.0 флешку и это вообще фиаско. За всю ночь ничего не обновилось. Не для этого система сделана. Теперь флешка официально переходит в разряд хранилища. Эта новость меня прям удручила. 
*** Беспокойство
Насмотрелся Школьникова про деньги и опять плохо работает флешочная ОС и начало трепать в груди, давление 161/97 чет высоковато. Плохо засыпал. Надо меньше смотреть про будущее. Оно неопределенно страшное. А потом думаешь про ограбление 91 и думаешь еще сильнее.  
*** Домики
Опять смотрел домики и это сплошное расстройство, информации нет, стоят дорого, все фигня. Может податься в деревню. 
** 25.01.2021 Пн
*** Ценовая политика
Вскрылось, что по работе надо сократьть расходы в 3 раза. Это уже ни в какие ворота. Надо всю концепцию переигрывать. А по другой работе заявили поминималками 0,2 млн. и мне сказали, что поднимут до 0,6 т.к. у них округление поднимит сумму до 1,0. Что-бы не писать округление вверх или вообще не округлять они готовы на порядок поднять затраты, я не понимаю.  
*** Протурбации
Договорился отдать на профилактику один комп и мне прилетела предьява, что я не спросил разрешения профилактировать чужой комп, потомучто на нем хранит свою нерабочую информацию другой человек. Я не понимаю.  
*** Прогулка
Вышел на обед попозже, а закончил есть синхронно с карп. Дошли до корпуса и пересекся с ИД. И позвала меня составить им компанию. Я с удовольствием это сделал. Просто светские разговоры. Но лучше, чем говорить с самим собой.  
*** SD
Провел эксперимент с карточкой и о чудо, обновление заняло всего час или полтора. Это реально рабочий вариант. Сама эта ОС мне вообще никак не понравилась. Заказал новую карточку, а эту пущу на эксперименты. Больше никогда не использовать ЮСБ в качестве железных устройств.  
*** Весна
И пришла в платье. Теплый воздух в лицо. Вскрылся асфальт. Как же хорошо. И это январь. 
** 26.01.2021 Вт
*** Поворот туда
На прогулке ИД совратили меня с пути и я потдался утехам живого общения. Переобулся на лету. Дальше светские беседы о былом. 
*** Человечки
Аф попросила помочь раскидать человечков. Сама сожгла слишком много человеков. Не видать нам баланса системы. 
*** Логистика на грани фантастики
Лена кинула на меня еще и организацию доставки бумаги, я помог ей с транспортом и послал нахрен, она пошла жаловаться на меня - смешные люди
*** Заложи начальника своего
По всем фронтам обрабатываю одного персонажа. 
*** Премии
Добился предварительного знания как считается премия. Не сходится с распоряжением. В три раза меньше, чем записано в законах. Не понятен механизм занижения. Все слишком непрозрачно.  
*** Грудастая ципочка
Димка походу наелся грудок, надо думать что-нибудь другое. Пол вечера орал как резанный, что грудка слишком жесткая. 
** 27.01.2021 Ср
*** Внезапная неожиданность
И отпросилась сегодня, а я сидел утром в надежде. Хотел срочно подписать бумаги, а Кн сегодня нет. Дима спирит позвал на ДРтортик, а я не пошел. Ака отпросился на завтра у меня.
*** Таблички
Подбиваю дебит и кредит и выходит какая-то лажа. Во всех работах концы не сходятся. Нет постоянного мониторинга. Нужно вводит системы ролинтехнолоджи. 
*** Дом
Посмотрел прогноз рынка недвижимости и дальше будет только хуже. Походу мой маятник качнулся в сторону дома. 
*** Жадина-говядина
Приготовил говядинки и она сегодня превосходна. В меру соленая. Варил ее полтора часа и буквально тает во рту. Надо чаще готовить говядину. 
** 28.01.2021 Чт
*** Отец героин
Ака слился, я его прекрывал, пиздлявый бабий язык его сдал с потрохами. А потом эти люди жалуются на бигбосов, что те сваливают по первому чиху. 
*** Шьёрт побьери
И сегодня опять нет, ходят слухи, что подскальзнулась, упала, очнулась, гипс. 
*** Карусель
Выехали в обычное время и пврковка была полностью забита, пришлось ставить в лесу на щебенку
*** Непорядочек
Пытался привести в порядок дела с человекоемкостью, а там уже резвится козел в огороде, разгребать эти авгиевы конюшни. А вообще надо написать считалочку версталочку до лета и использовать ее как аргумент
*** Высокое близкое
Посмотрел еще, Высокое ближе чем квартира от работы, быстрее бы весна и велоразведка
*** Перебезчик
Встретл чувака с этажа, тот переехал на соседнюю работу и хвалится, что там все круче и вообще медом намазано. Сдается, если через два с половиной года этот мир не рухнет, надо пересмотреть трудовую деятельность
** 29.01.2021 Пт
*** Бездельники
Что-то я разнервничался, когда эти нач.отдела не выполняют свою работу. Поспокойнее надо быть.
*** Профилактика
Отнесли компы на профилактику, цирк с конями - накрыть корпус крышкой и забыть
*** Календарик
По видимому календариковая промышленность не планировала 2021 год и достать приличный толстый перекидной - не такая простая задача.
*** Апгрейд
Флешка встала в фотик и теперь у меня 4к фоток в запасе, я конечно и 2 не набивал за поездку, но все-же. 32 флешку пущу на ОС.
** 30.01.2021 Сб
*** Работа
Опять поехал на работу. Все кругом не работают, хотя стоит это все в 2 раза дороже. Бесит. Написал служебку. Поправил таблицу. 
*** О Высоком
Уже несколько дней думаю о Высоком, как о альтернативе квартиры в Туле. Хорошая природа, частный дом, газ по забору. Отсутствует интернет, непонятно с водой и канализацией. Приемлемая цена. 
*** Ремонтер
У мамы сломалась стиралка. Димка засыпал лимонной кислоты и она заработала. Мама фигачила туда соду (советы из интернета) и все трубы закоксовались. 
*** Лемита
Дочитал "Маленького прица" и начал "Сумму технологиий" - наконец офигительная фантастика. Наконец я понял, за что Лема считают в ряду великих. 
*** ЗОлет
Кате 30 лет. Это уже как-то напрягает. 
*** 
** 31.01.2021 Вс
*** Снегочистка
Навалило снега и пошел чистить дорожки. Навык чистки снега утерян. Ломит спину на скручивание. Но сама идея прикольная.  
*** Алармист
Электронный термометр сломался и показывал -12. Папа с утра бегал и орал, что на улице ужас ужас. 
*** Занос
Снежная каша на дороге. По трассе пришлось уворачиваться от пидора обгонщака и пару колебаний машина совершила. На повороте в городе просто машину стало разворачивать. Страшное это мероприятие.
* Feb
** 01.02.2021 Пн
*** Показуза
Решил показать свои считалочки людям - люди - это тупые мрази. Никто нихрена не понял. 
*** Солнце
Красота утром, красота днем. Последние лучи солнца в лесу. Кросота. Все деревья в белом. Снег хрустит. Дорожки не чищенные.  
** 02.02.2021 Вт
*** Зараза
Анька самовыпилилась. Отвалилась ее поездка и у меня только сожаление, что ее не будет меньше, чем запланированно. Боже как же хорошо без этого бесконечного радио. 
*** Пусть с другим она гуляет
Опрокинули с доброй традицией. Д скинули на командировку, и И ушла гулять с Антоном. На пересечениях я просто продолжил свой путь в одиночестве. 
*** Счетчики
В то время как другие мечтают, я считаю. Игорь пожаловался, как бы нам посчитать деньги. Я тыкнул его носом в считалочку. Все покивали и проигнорировали. Пришла настоящая смета и там нашли замечания. В моей никто не смотрит ничего. Просираем сроки и прикидываемся, что не умеем считать. Идиотизм. 
*** Кускус
не удался. Просто подгорело. Надо попробовать не на ребрышках. Идея тоже так себе. Просто макароны. 
*** Солнце
** 03.02.2021 Ср
*** Совещание
Тупость и порожняк. То, что можно решить за одну секунду и договориться за минуту, тянется уже три месяца и ничего нового не рождается. Мозговые слизни поразили всех вокруг.  
*** Расчеты
Люди тупые. Никто нихрена не слышит. Без теории нам конец. 
*** Подпись
Забыл, что сегодня среда, за сб расписалась И и я даже не вспомнил, за что надо расписываться
** 04.02.2021 Чт
*** Вежливость
фраера сгубила. Предложил Кате прогуляться в обед и она согласилась. Пол часа я был обречен слушать про непорядочек
*** Мисскоммуникация 2018
Как же тяжело с тупыми людьми
*** Мясо
Хотел сварить рис с рыбой, порылся в ящике и не нашел там риса. Пошел в магазин, накупил мяса и рыбы на 4кр. Принес домой рис и вот он лежит упаковка риса в ящике, точно такой же. Ну и хрен с ним, будет два риса.
*** Одежа
Собрался в магазин и оделся по быстрому, толстовка без майки, ветровка, чуть было не натянул ботинки без носок. Но нижнее белье не просто так придумали, без наго плохо совсем.
** 05.02.2021 Пт
*** Слишком сложно
Кн пожаловался, что мои отчеты ошибочны и слишком сложны - сделай все сам, мудила
*** Скользящие
Ака не явился сегодня, на меня льются всякие идиоты со своими идиотскими идеями
*** Халатность
Незадумываясь облакотился на сломанный стул, отбил плечо и отнес стул на 8, эти двое недоделков развопились, что это их гавно и они его еще недоели.
*** Стейк-миньён
Запилил вкуснотищу. Еще перетерли с И проблемы рынка и питания. Когда речь зашла о пище духовной, я рассказывал о будущем, которое будет, а она о романах.
*** Довоз
Антон посигналил, когда я шел домой, и предложил подвезти. Я кивнул, что хожу не потому-что не начем ездить, а потому-что гуляю
*** Время вверх
Насмотрелся Дугина и его пересказ концепции вертикального времени. Будущее на ступени выше, прошлое - инферно, настоящее - настоящее. И очень мне эта концепция понравилась. 
** 06.02.2021 Сб
*** Разрыв шаблонов
Пришел на работу, по пути догнал Кар. Но дверь в кабинет закрыта. Открыл, переоделся и пошел в женскую половину, а там пустота. Что делать, такова жизнь. Опять парочка ворковала весь день и смотрели фильмы целый день из одного наушника. 
*** Ступеньки
Насмотрелися ютуба и решил дернуть 14 этажей зарядку. Ноги слегка зибились. Надо попробовать продолжить эту тренировку. 
*** Расчеты
Долго думал, чем бы заняться, решил заняться объединением механизма планирвания и сжигания трудоемкостей. Запилил прикольную таблицу, порадил еще немного интересных мыслей по поводу управления. 
*** Заносы
Поехали домой. Солнце лежит прямо на горизонте. Как только въехали в район на дорогах появились заносы и поземка. Уже на апендиците дорога разлинована на три калеи и во время обгона машину немного занесло, стремно. Двор не чищенный, а утоптанный, а у ворот расчищено и перепад сантиметров в 30. Приехали в четыре, посмотрели сериальчик, в шесть все еще было светло, к девяти мороз уже был под 20 градусов. Красотища, прямо вечера на хуторе близ диканьки. Еще один повод брать частный дом. 
** 07.02.2021 Вс
*** Анализы
Мама предложила сдать анализы на онкологию. Как-же это все странно. Сдал образцы. Теперь думаю об этом. 
*** Лем
Бахнул вторую половину книжки. Теперь вся фантастика - тусклая калька с этих рассуждений. Наконец я полюбил читать Лема. 
*** Солнце
Погода прелесть, немного холодновато.
*** Высокое
Ссылаясь на хорошую погоду, пошел гулять до Высокого. В лесу шикарно. Погода прекрасна. Новое село скучновато, газ есть, дороги чищенные через одну. Половина домой недостроена. Натоптал ноги и изрядно замерз. Нет ощущения родного. 
** 08.02.2021 Пн
*** Месяц
На улице 17 градусов, чистое небо и почти растаявший старый месяц на горизонте
*** Аутсорс
Подрядил Марию править код. Боже, как удобно делать все несвоими руками
*** расчихан
Димка с сопляси и заразил меня
*** Лошадка
Вечером только и рассказывал анекдоты про лошадей
** 09.02.2021 Вт
*** Секвенция
Урезаю людям зарплаты, в первую очередь себе.
*** Имбицил-программист
Зашел в пятнашку и за три предложения унизил человека, живущего в двацатом году
*** Староверы
Пытались с Марией запустить софтину на ДОС. Это боль и страдания. Дискета завелась только в ее руках. Софтина завелась в бат но не завелась в ехе. Решили, что на сегодня хватит.
*** Унижения
Подставил Андрея и слился, тритировал Геннадия, обвинял в лицемерии Аркадия, защищая Антона (пустое место) обвинил И в необоснованности, разрубил гордиев узел в инсенуация И от Ака анекдотом про беспорядочрые половые связи
*** Люди для себя
Стал склорять К к деторождению и семейным ценностям и натолкнулся на сказки о прекрасром будущем и жизни для сабя
*** Нервная сеть
Димка мечтал, когда нейросети будут снимать кино по кригам, я сказал, что у каждого в голове есть такая нервная сеть, но его почемуто ракой ответ не устроил
** 10.02.2021 Ср
*** Недосып
Из за заложенного носа не спал с 2 до 4, кроме общего неадекватизма от простуды не чувствую усталость от недосыпа
*** Алармисты
И сразу заподозрила меня и отправила в больнрчку
*** Додельный
Доделал все срочные дела и слился от всякой ереси. Гнида недоделанная манипулирует и склоняем меня к программизму на матлабе, но по мне лучше программизм на человечках - непроторенная тропа, темболее качество наших начальников оставляет желать лучшего.
*** Кружки
Помыл чайные кружки. теперь в них можно смотреть на звезды, а не черная дыра, что была раньше
** 11.02.2021 Чт
*** Отсыпной
Выспался наконец-то
*** Порядочек
Как божественно приятно заниматься своими делами
*** Архив
Нашел таки утеряный архив моих старых работ
*** БП
Нарисовал Димке коробочку под блок пиитания, получилось очень хорошо.
** 12.02.2021 Пт
*** Пурга
На улицу страшно выходить, метет уже целый день и обнщают до понедельника, дома завалило по окна, город в пробках
*** Уборка
Немного подмел, купил коврик доя ванной, 
** 13.02.2021 Вс
*** Сон на животе
Поспал на животе и это так неудобно - весь вес тела отлеживает грудь и все затекает и шея неудобно, а еще пару месяцкв назад я только такой метод и практиковал
*** Линзы
Достал из своих старых закрамов линзы - у меря офигительная коллекция стекол.
*** Солнце
После таких снегопадов оород встал и красиво освещается солнышком
** 14.02.2021 Пн
*** Досуг
Посмотрел лекцию, как проводить досугипо Аристотелю - поспал на ней - очень хорошая лекция, очень полезный досуг
*** МОБ
Наткнулся на очередную эзотерическую концепцию с табличками
** 15.02.2021 Вт
*** Синий
Встал утром и в окне узрел идеальный синий, потом днем этот цвет неба менялся, но всеже оставался прекрасен
*** Выписка
Пошел и выписался с больничного. Переучелся с Воловской поликлиники на местную. Встречил коллегу. Место так себе
*** З/Работа
Ака позвонил узнать что как, это так подозрительно.
*** Сон
Поел вкусную пшенку с тыквой и вырубился спать
*** Предел безделия
Стало скучновато. Может и правду сокращать рабдень.
** 16.02.2021 Ср
*** Мороз
-22
*** Разрядка
встретил какого-то бомжа и тот сказал, что наша работа выполнена.
*** Повелеваю
Кинули мне еще какую то работу, которую я не делал. Надо разбираться
*** Закат
Шел домой в прекрасный закат, подсвеченный дым из труб, рассеяный свет
*** Контроль
Мама палит в камеры каждый чих
*** Деревенщина
И саазала, что мне надо отдохнуть за границой себя
*** Евангелисты
Дима подцепился к моей основной грппе
*** Банк
Стряс денек с народу на 23 - бумажные деньги уже ни с кого не стрясти.
*** Цифровизация
Дмитр попросил меня загнать всех бездельников под контроль
** 17.02.2021 Чт
*** Должек
Пинаю этих бездельников по их долгам, а они колятиной нихрена не делают.
*** Зарплатка
Посмотрел свою зп по годам и "зарплата - это не то, что может мотивировать, это то, что может демотивировать" - получил ы 2020 как ы 2016 и три года подряд зп сокращается на 50к в год
*** Оглашенная
Вернулась наша BTM (big teets meter) сегодня на удивление спокойная
*** Солнце
Ухожу в закат уже второй день - красота
*** Халтурщик
Мужик чистил крышу на магазине и недочистил - взялся фотать работу с ракурсов, где не видно невыполненную работу - все люди гниды
*** Обед
Ака увязался за мной на обед и хлебал и всячесаи мне не нравилась его культура преломления хлеба
*** Халтурщики
Мужик чистил снег на крыше и не дочистел половину - халтурщики
** 18.02.2021 Пт
*** Коллективная дезответственность
Начальство само сообщило, что сверхсрочную работу что-то уже можно не делать
*** Ретропараавоз
Женя отмечал бездник, было забавно
*** Безды
Наезжал на Лену Панфилову Мл, а у нее сегодня ДР
** 19.02.2021 Сб
*** Подсидел
На утренней сходке подорвался на телефон и мое место заняли. Манипуляциями и обманом я подсидел ака и он обиделся
*** Облава
Мария позвала есть пироги и нас накрыла масочная полиция - теперь я еще больше не люблю это место
*** Баран
Сделал гарнир, пожарил баранину, попробовал баранину и в голове вспыхнули воспоминания из далекого детства, когда к нам приехал цирк и папа купил нам шашлык - это был шашлык из баранины - 25 лет я не пробовал ничего такого. Ох уж эти флешбеки)
** 20.02.2021 Вс
*** Отметили
Очень хорошо отметили 23, накрыли бутердный стол, пиццу освоили на половину, попробовали абсент, были разговоры о высоком и о бытии, о том, что я потерялся немного. 
*** Поцелуи
Под закат И подарила мне невинный поцелуйчик
*** Беспалева
Вечером походу даже не спалился, что я наклюкатый, но спать отвалился при первой возможности, да и вообще большую часть вечера, что отведен на просмотр ютуба я просто дрых.  
** 21.02.2021 Пн
*** Домой
Поехали домой, погода так себе. Через пургу в небе пробивается диск солнца, холодно, поземка. Машины едут в снежном облаке. 
*** Свинобойня
Папа уже совсем не справояется с поросем. Порось еще пол часа бегам и хрюкал. Пока разделались с ним, я околел как сволоч. В итоге весь двор залит кровищей. Папа уже не тянет и я предложил больше не водить свиней, если не можешь их пустить в оборот. 
*** Сугробы
Димка пытался заехать на подготовленный пьедистал из снега, но машина подминает его - начистили площадку ровно в машину, ох и утомительное же это занятие. Но на текущем слое машина не проваливается, и Димка зачем-то накапал калию (говорит, что утрамбовывал снег). Как же мама с папой почистили всю эту площадку перед двором. 
** 22.02.2021
*** День книги
Весь день придовались прелестям чтения, Димка начал Анафем, капризничал весь вечер. Я начал Дюну - гораздо интереснее чем фильм, почитал Город и город Мьенвеля - вполне недурно
*** Искры
Димка неправильно подлючил реле инкубатора и выбило пробки, второй раз вроде работает.
*** Подстригся
*** Орион
За долгую городскую пасмурную зиму сегодня при большой луне на небе зароделся Орион и иже с ним - в это морозное зимнее красота
** 23.02.2021
*** Холодяра
-25оС. Солнышко фигачит во всю
*** Катя
Мама передала Кате посылку, катя не была дома и заехала к нам с каким-то чуваком (стремный - но почему я достаточно ниче так сижу один)
** 25.02.2021
*** Эта музыка будет вечной
Приехал Илья и у нас незатыкаемое радио. Невозможно работать. Приехал Коля - тот же результат. Заткнитесь вы уже.
*** Апгрейд
И включила комп и он не включился. Быстро пересадили на новый. А она вертит носом - не такой уж и быстрый. Все чрезвычайно вовремя сделано, алюди неблагодарные твари.
*** Бекап
Дима под шумок решил пересесть тоже. Началась эпопея боданий с пятнашкой
*** Флорафаг
Эта тупая пизда выкинула мой цветочек.
*** Поехала крыша
Димка все ходит и рассматривает трещины. Так и живем. А еще обеща меня выгнать, если я не сделаю блинов.
*** По чем холопы
ака сдал меня как дешовую грузовую силу, за одно узнаем пути птдхода и дислокации матершинника всая руси
** 25.02.2021
*** Дождь
Утром было -9 оС и шел дождь, вечером дороги поплыли и снежная каша под ногами
*** Ремешек
Приехал из китая ремешек для фотика - редкостное ширпотребье, но и хрен бы с ним
*** Фонарик
Приехал и фонарик для велика - походу в моргающем режиме я не смогу ездить, но так он вполне мне нравится
*** Математики
У И не работает Драганддроп в аутлуке и целая команда спецов из 15 борятся с этитм - дебилы б**ть
** 26.02.2021
*** Ледоход
Все дороги превратились в ледяной лом и машинки никуда не едут. Дороги текут и я очень рад, что одел сегодня прорезиненные сапоги
*** Грузовые инженеры
Подрязили, с 0900 до 1430 грузили. Организация на грани фантастики - приехала маленькая газель. Домик вообще не очень, новый красивый. Жинка так себе. Задолбался знатно. Только по конец придумали схему с челночным лифтом. Находил сегодня 20000 шагов. 
*** Вынос
Наша выгрузка ящиков совпала с выносом тела. Приехали мы в газельке и я пошутил по мексиканских нелегалов. Подождали, пока попращаются и продолжили грузить ящики.
*** Плюшки
В Лагуне работает пекарня, не знаю что там делает, но запах обалденный. Надо в каджом ключевом месте по пекарне.
*** 32
Посмотрел ролик на ютубе, где автору стукнуло 32, и тут начинается экзистациональный кризис.
*** Ремешок
Сегодня как к месту полная луна лезет прямо в окно, шелкнул ее с ремешком и это реально гораздо удобнее. Еще удобнее с мотоштатива, но всеже
*** 91570
Узнал, что фотик отстрелял 91570 закрытил затвора, при ресурсе в 100000
** 27.02.2021
*** Семейный марафон сериалов
Парочка все больше походит на семейную, уже в одно ухо смотрят сериальчики и хихикают. Унываю.
*** Фотограия рабочего дня
Косвенно сообщили, что надо делать фото дня, люди озабочены
*** Программист
На меня пришла телега, что я использую только 7 процентов компа. Написал прогамму умножающую на 2 и сжирающую весь процессор. Я уберпрограммист.
** 28.02.2021
*** Погода
То снег, то грибной снег, то солнце - погода сегодня прекрасна
*** Уборка
Димка затеял уборку, и я тоже поучаствовал
*** Фото
Поделал фото могоды, но на телефоне их не обнаружил, или потерялись при переносе, или не сделались.
* Mar
** 01.03.2021
*** Никамуникабельность
Отсутствуют И, Д, Аня. Понаехали Алексей и устроили с Болотом конкурс болезней.
*** ТО
Пошел на медосмотр, сказали что во мне 83 кг веса и 180 см роста, еогда по моим показатнлям 88 и 185
*** Норма
Выкатили приказ о норме без прилюдий и вазилина.
*** Бесшапочник
Тепло, хорошо. На обеденнгй прогулке снял шапку - пока рановато, но очень хочется
** 02.03.2021
*** Очередь
Продолжил ходить медосмотр и прям бесит меня суперпозиция некоторых имбицилов усидеть на двух (трех) стульях одновременно.
*** Вопрос не в бровь, а в глаз
Алексей пытался рассказать о своем невероятном потанцевале и я крайне жестко пошутил по этому поводу
*** Оброк
Хожу, трясу с людей мощные компы
** 03.03.2021
*** Кровопийцы
Наудивление легко и быстро сегодня дошел комиссию.  
*** Агрессия
Собирал данные про компы, какие же люди агрессивные нетуда
*** Занавес
Димка наконец прикрутил гардину к стене. Теперь не на брусочках все это
** 04.03.2021
*** Работка
Без начальства работа идет планомерно
*** Снег
Пошел снег и зима откатилась обратно
** 05.03.2021
*** Решения
Насаждаю демократию всем, принимаю самостоятельные решения, эти людишки никчемны.
*** Тортики
В честь 8 марта поели тортики. Все остальное время сидели грусные, чтотбыли только тортики
*** Грусть
И сегодня весь день отключенная. Позвал ее гулять, она сказала мне нет, и пошла гулять с антоном - а мне уже как-то всеравно, только больно немного.
*** Боль
Что-то давление у меня хреначит до небес, постоянное беспокойство в груди. Решил начать закидываться атенто
*** Штатив
Пришел, вполне годный. Хлипковат, но для дела сойдет. Надо сделать ему голову.
*** Кабель
А вот кабель мелковат, надо чтоль мини
*** Цветочек
Купил цветочек, хочу подарить его И. Если нет, оставлю себе. Аня выбрасила мой цветочек и поливалку - тупая пизда.
*** Бездник
У Кн ДР, как то все нелепо вышло сегодня
*** Соблазнилель
На мою шутку, что "поздно меня уже соблазнять, я сам кого хочешь соблазню" И посмеялась смехом с издевкой и неверием - обидненько
** 06.03.2021
*** Цветочек
Подарил И цветочек, она сказалА "ой какой милый, надо его пересадить".
*** Карты на стол
Рассказал аке, чем сейчас занпмаюсь. Он сказал, что паррия с перестановкой сыграла в партию в Новичек из одной богомерзкой компании.
*** Светофор и бочка
Димка что-то не в духе сегодня. Собрал красный светофор и возможно штраф. На заправке бочка бензовоз и взболомученый бензин. Что-то пошло не так
*** Декаданс
Посмотрели "последний богатырь 2" - это все. Конец русской культуры.
** 07.03.2021
*** Сон
Все спят целый день. Я дослушал книжку
*** Покраска
Покрасили маму. 
** 08.03.2021
*** Обрезание
Обрезал две груши немного. Яблони обрезать уже не знаю как.
*** Траншеекапатель
Откопал западную стену дома отсугроба. Там чет все заледенело.
*** Погодная турбулентность
Погода меняется от солнышка и капели до пурги за пять минут каждые пять мминут.
** 09.03.2021
*** Мороз
-10оС, завтра обещают до 20. Вот это погода. Утренний рассвет и звездные ночи. Вечером вышел с работы и морозец прям хватает за ноги.
*** Туше
Пошел к Кн с пакетом бумаг на пятнашку. Совсем лютые предьявы закономерно отклонили. С остальными будем работать. Укол про премии пришелся плохо. Надо доделать модель УР.
*** Транзакционные издержки
Покупал сухари и наблюдал как пришел мужик-сборщик заказов (который сидит в стоимости моих печанек) и продавец из головы по памяти делает заказ, хотя можно ввести мониторы и модель принятия решений, оптимизировать логистику и сократитьь издержки. Если уж работаешь на капитал, делай это хорошо.
** 10.03.2021
*** Эй тореро
Машу красными тряпками перед пятнашкой. Надо почистить комп.
*** Доверие
На прогулке И поинтересовалась, когда я пойду в бассейн. Я рассказал про давление обстаятельств и артериальное, пря катарсис из-за того, что можно комуто рассказать такое
** 11.03.2021
*** Распоряжение
Написал распоряжение - люди неадекватно на него реагируют. Интересно посмотреть, как люди будут реагировать на ответственность.
*** Коробочка
Пришла коробочка для ресбери. Надо доделать вертолет и занятся линухом. Скачал хакер и понял, что без праксиса я не развиваюсь, и это удручает
** 12.03.2021
*** Таблицы
Опять закапался в своих таблицах. Пошел к И посидеть и думал о таблицах
*** Ощущается как
Утром было -16, днем -6оС но из-за ветра все покрылись сосульками
*** Персик
Нажрался немытой куриги. Живот крутило как вертрлет
** 13.03.2021
*** Тройничек
Сегодня только втроем сладкая парочка и я. Еще они устроили акт преломления хлебов и И выкатила блины с сыром и медом - это было прикольно.
*** Трудоемкость
Весь день стдел и собирал трудоемкость. Еще причесывать ее и причесывать
*** Виски
Димка очень прикольно придумал подарить папе виски и подарок пришелся к месту. По вкусу я не понял как люди вообще говорят, что пойло может быть вкусным. Папа сразу согрелся (а до этого всю неделю мерз) а мама розовая сидела вязала
*** Весна
Так и не приходит. Пурга, валит снег, мокрая дорога, морозец
** 14.03.2021
*** Зима
Так и не собирается уходить
*** Стрижка
*** Инкубатор
Димка запилил инкубатор на новом контроллере
*** Прощение
Что то болит позвонок, и колет в груди и скачет давление и мысли всякие роятся в голове про прощание и наследство
*** Космос
Порядочек должен быть
** 15.03.2021
*** Закидоны
Опять меня закидывают бумажками
*** Ананлитика
Попилил пол дня трудоемкость, плана как планировать особо не появилось
*** Кабель
Эд вообще не очень ладит с технологиями. Пытался засунуть типц в микроюсб. Потом чин не смог заказать тачку. 15 деградирут
*** Морские гады
Магаз с мясом закрыт, альтернативный на переучете. Купил морских гадов и запилил макарон, но удовольствие такое себе.
*** Шмот
Пришли шерты из китая, это первые и последние одежда которую я покупаю в интернете. Такое гавнище, просто слов нет - крой отсутствует, ткань не для шорт. не рекоменлую.
** 16.03.2021
*** Комяк
Коля впрнулся из своего миниотпуска полуженатым человеком и рассказывал прикооы тамашней жизни. Летом будем ждать его осемействлении.
*** Подписант
Помогал одному специалисту потделывать его собственную подпись. Очень забавный вариант
*** Эффективность
Собрал нас ААА на совещание и рассказал про космические корабли. Поручил за две недели разобраться с тем бардаком, что они навводили за десятки лет
*** Успеваемость
Еще и успел доделать бумажку которую деоать неделю
** 17.03.2021
*** Недосып
Лег спать в 10 и проснулся в час, потом всю ночь не уснул, и только под утро прикорнул. Днем ходил несколько отзомбяченный.
*** Табличка
Опять неподнимая головы проторчал целый день в табличках
** 18.03.2021
*** Настройка
Кн настраивали комп - ну он и тормоз, а по характеристика нормальный такой - ssd делает свое дело.
*** Культура
Кинул табличку начальникам (в надежде, что они умные), ан нет. Так еще и один заблочил работу всем остальным - дебиля блять.
*** Поручение
Попросил Филипа заполнить табличку, и он с удовольствием сделал это, я прям неловко себя почувствлъовал эксплуатируя человека не прилогая для этого усилий.
*** Склянки
Дима отхватил себе химпосуду и это прям вызвал фурор.
*** Брейншторм
Посидели втроем побрейнштормили и вспомнили что-то, чему нас учили. Получилось неплохо, осталось сделать.
*** Интерфейс
Сменил интерфейс в кали на в10, а обратно он не переставляется, и меня еще очень бесить zsh, но так даже может иилучше. Надо изучать.
*** Конкуренция
Позвонил Леше, предложиь поболтать. Он - индивидуалистическая сволочь - сказал идите в жопу.
** 19.03.2021
*** Между строк
Нашел в приказе все вопросы и ответы к посулу ААА.Мою теорию никто не хочет слушать, я откровенно провоцируя пытаюсь докричаться до них - и тишина
*** Доброта
Зашел к 55 узнать, сделал ли тот свое домашнее задание, он отбрехался и я посмеявшись ему в лицо ушел. Далее вечером на мой звонок он очень по доброму пытался обьяснить мне, что файл не сохранился и ему надо еще несколько минут, это "Паш" повернуло мое отношение к нему на 27о :)
*** Картинка
Очень классный снегопад и сосновые аллеи.
*** Шнурок
Эд подряжает меня на элементарные действия с компами, это очень необычно.
*** Помощь
ААА попросил помощи, а мы превратили все в соревнование.
** 20.03.2021
*** Марафон стратегии
Целый день писал Эффективность. Получается не очень. 
*** Лужи
Такая отличная погода. Вчерашние лужи покрылись тонким льдом, можно по гему ходить и проламывать своим весом. Солнце. Идя с работы попал в промежуток, когда минут пять ни ехала нм одна машина и наступило блаженство - тишина, птички поют, ручьи журчат. Как я скучаю по деревенской простоте.
*** Релокация
Узнал, что Саша слился в мск в рекламу, а Яков в процессе в мск в рти. Ну пипец - один я работаю
** 21.03.2021
*** Пылесос
Димка сдела циклон-фильтр для пылесоса.
*** Погода
Легкий морозец и солнышко сменились тучками
*** Бездомный
В эти выходные не поехали домой, Димка выматывается за рулем и мы ездим туда просто спать
** 22.03.2021
*** Некомплект
Дима не пришел и разговор не заладился
*** Ключник
Ака заперли на работе и мне пришлось возвращатся на работу пешком. Был очень зол и устал
*** Кашка
Брал обед с собой, это спокойнее но совсем не интересно
** 23.03.2021
*** Перелай
Обсуждали поездки и бабы устроили перелай. Взял власть в свои руки и запилил сайтик
*** Нейросети
Пр обсуждал результаты НИР с усом и тот вертелся как уж на сковородке. Потом Пр спросил у меня что да как.
*** Непонятки
Дима сказа, что я сделал непонятную презентацию
*** Корзина
Надо закупаться обьектвами на поездку и купить голову на штатив и написовать голову мото. И еще лазер для фоток с лазером.
** 24.03.2021
*** Наряд
Попробовал новый метод замыкания цепочек на себя путем введения екселек и автоверстки против вордиков. Через несколько актов помощи все вполне получилось.
*** Транс
Совещание было наполнено водищей. Как интересно быть в центре урогана.
*** Сайт
Запилил сайт про турпоездки
*** Качели
Утром опять -6оС, уже пару дней как все отвыкли от таких морозов, а днем у меня возникло (и реализовалось) стойкое желание снять шапку и перчатки, пока шел домой
*** Обед
Пошел на обед немного позже обычного в начальничий час и тут морды уже поинеллегентнее
** 25.03.2021
*** Операционка
Придумал, как доложиться, никого не обидеть, и продвинуть свои идеи. Организация, как операционка. А отрасль как сеть.
*** Мошенники
Позвонили из банка и стали втирать всякую дичь, и я начал вестись на это. Сбегал в банк и они меня там успокаивали
*** Марсиане
Вчера опять открыл книжку про марс - они прекрасны
** 26.03.2021
*** Прогулка
Пошел на работу пешком. Весь употел, пока дошел. Скинул шапку. Ножка заболела. Поблагодарил И коробочкой конфет. Вторая прогулка в обед омрачилась Димиными предьявами, что он единалично жаждал погулять и поговорить с И. Моя контрагрументация была сильноманипулятивна.
*** OrgOS
Поболтали о будущем. Я рассказал свою концепцию орг операционки - сказали, что слишком прогрессивно. Соединение в CyberNet даже не рассказал.
*** Побег из курятника
Что-то переклинило у меря в мозгу и я свалил с работы на час раньше. Быстро опомнился и через 15 минут уже вернулся. Закрыл все дыры. Но очень странное поведепие для меня
*** Шутка
Приклеил новые фоточки на стену фоточек. Должно быть интересно. Еще показал аке рефы по графикам.
** 26.03.2021
*** Алфавит
И пришла с надписями на майке и я целый день читал их
*** Шутка
Мои плакатики никто не заметил, пришлось долго и нудно обьяснять их им
*** Преза курильщика
Ака выкатил свою презентацию состоящую целиком из претензий. Очень стремно
*** Божественная яишенка
Димка насмотревшись дальнобоя из ютуба решил приготовить яишницу. Яишница получилась ниче так, но вот колбаса целикос состаит из крахмала
** 28.03.2021
*** Полный день
Проснулся ни свет ни заря. Встретил рассвет. Целый день матался по магазинам.
*** Шмот
Купил приличные шорты, брюки, плащ, ремень, звоночек для велосипеда. Прошел мимо, а надо теперь вернутся, и купить веловетровку зеленую, толькотцена у нее конская. Хотя я за еду на пару дней сегодня отвалил столько же. Димка затариося ботинками, штанами и футболками. Еще купили воздушные каналы для курятника.
*** Хаос
Ютуб хреначи тредложку очень старых видео. Это странно, но интересно. Надо скачивать интересное видео, а то вдруг интернет кончится.
*** Ходуненция
Прошел пешком от дома до макси и далеее и обратно. Подустал немного. Весна уже на пороге. Бродил без шапки. Люди вываливают на улицу.
** 29.03.2021
*** Разрыв
Дима попросил больше не занимать в обед их с И время. Ну и ладно.
*** Плащ
Новый плащ очень ниче так. Я в восторге
*** Совещание
Было совещание по ААА в расширенном составе. Слишком избыточном для такой работы. Люди - просто балласт.
*** Техпотдержка
Опять звонили из банка. Просто положил их в карман.
*** Ультразвук
Димка забрал посылки из китая - ультразвуковой испаритель, который рвет пальцы и бьет фантанчиком и маленькая видеокамера с сверхнизким разрешением и не подключающаяся к телефону. Сплошное разачарование - как мои шорты.
** 30.03.2021
*** Окуляр
ака попросил вернуть окуляр, я его упаковал и встретил аку на парковке, где все мои беспокойства по поводу кладовки ушли в мнимую область
*** Кривой
ака раскарячил машину и Димка встал по разметке. ака долго не мог дойти своим умом, зачем надо соблюдать разметку.
*** Ирония
Стоически превозмог отлучение от социалочки, не вписался в тусовочку. И тут вижу как ИД и Антон устроили тройничек.
*** Мани
Пригнали к нам женщину из цен и она как разумный человек ничего нам не рассказала
*** Поздняк
Пошли на совещание к П и досидели там до восьми. Первый раз я так развлекался. За 10 лет стиль повествования не изменился ни на милиметр. Открыли маленький лайвхак - с нами была Лиля, и П был сама учтивость. Вечером очень брадовался, что взял с собой перчаточки. 
** 31.03.2021
*** Дождь
Первый дождь. Уже почти все растаяло.
*** Репродуктивный МРОТ
Только утром думал, что надо все дикретным платить МРОТ и детям до 18 лет тоже и вечером прочитал новость, что малообеспеченным выплачивают МРОТ. Кто-то тырит идеи прямо у меня из головы.
*** Шарик
И принесла шарики на работу и три здоровых лба играли в волейбол им
*** Безответственность
На совещание все опоздали. Мат ездит мне по ушам, что я не запускаю бумагу.
*** Носочный кризис
Утром использовал последний носок. Хотел купить еще, а в стране, в связи с мобилизацией, закончились черные носки. Пришлось стирать
*** Перемудрили
Ребята настроили ексель так, что наши тетки нихрена не поняли и справедливо послали нас нахрен. Пришлось разруливать эту ситуацию.
* Apr
** 01.04.2021
*** Сублимация
Поболтал с И и самопридумал игнорировать происходящее. Немного поработал психологом. Пооучил от нее историю про ее мужика, деревенских дураков и сложности напоить ее. Прикольно.
*** Капитан-Америка
Ака сегодня нервный. Д наточил карандаши с двух сторон и ака наорал на него. 
*** Пицца
Сережа проставился за ДР просто положив на стол после обеда две пиццы.
** 02.04.2021
*** Перенос
Время совещания перенесли пораньше и это мракобесие было ужасным. Мою презу не показали, но заметили.
*** Снегодождь
Погода сегодня так себе
*** Добавочный
Рассказали, как позвонить на работу
** 03.04.2021
*** Фем
Набежали курицы, начали пиздеть. Маша рассказывала про свой маленький бизнес, что ей некуда девать дома. А потом прпставали ко мне с моей едой.
*** Бобры
Вдоль дороги почистили кусты какой-то адской машиной, которая превращает в мульчу ветки и стволы леревьев, без разбора.
*** Борец
Папа рассказал историю, чио у него есть 0.6 акций компании, и что он хочет их обналичить. Его понимание происходящего на низком уровне. Но больше мне понравилась позиция невмешательства Димки. Очень аккуратно он не стал брать ответственность за советы. Папа еще рассказал, как он героически помогал раскрыть обман бабушки - там понимание было еще хуже. Учиться хорошо. 
*** Снежный покров
В Туле уже почти все растаяло, в дома стойко все поля под снегом, а в саду вообще сугробы.
*** Ложки
Хотели починить тумбочку, но не понятно как ее крепить.
** 04.04.2021
*** Советы
Вчера пап спрашивал совет по вопросу акций, мама спрашивала сегодня по вопросу трудоустройства. Тяжко им без опоры.
*** Ящик
Сделали направляющие в ящике с ложками. Заставили маму разобраться в нем. Теперь выглядит нормально. Димка захотел поменять и второй ящик. А я захотел купить коробок для маминого добра и сделать модели мебели.
*** Погода
До +12 от +3 днем, солнце, возмоден снег с градом. Погода мотало туда сюда, в основном хорошая
*** Несовместимость
Выяснил, что у И кенон и мой майский фототур пока подвисает. Надо покупать.
*** Ветки
Пошел погулять в саду и тут понеслось. Решил обрезать виноград, Димка принялся за яблони, я принялся за яблони. Все устали.
*** Земля
Машина притонула и распахал пол двора. Надо более интепсивно выращивать там траву.
** 05.04.2021
*** Галстук
Пошел сегодня в белой рубашечке и галстуке, только Пр сказал о нелепости происходящего, остальные спрашивали, что я такой нарядный
*** Пирожочек
Ака проставился за ДР и свалил. Мне пришлось переться к несвоим и развлекть их историями
*** Программис
Сижу пишу приказ как программу.
*** Критик
Рассказал о происходящем Пр, он поржал и задал кучу правильных вопросов. Понимания не прибавилось. 
** 06.04.2021
*** План
Опять взялся за верстку планировщика
*** Шуз
Переобулся, возможно рано. Но такая легкость. Быстее бы лето
*** Пояс
Смастерил из стропы и полуколец пояс на китайские шорты.
*** Колпачек
Порылся в коробке и нашел колпачек на карандашь. Закрыл гештальт.
** 07.04.2021
*** Утреннее чтиво
Проснулся рано и воткнул в уши книжку
*** Одиночество
И сегодня не пришла и без нее и поговорить не с кем. Целый день люто кодил версталище в екселе. А дома еще смотрел про матмоделирование - занятная штука
** 08.04.2021
*** автоматизация
Завяз в автоматизации. Не могу разрубить узел. Нужен какой-то стимул.
*** Зеленый
Отжал у Димы коробочку зеленого чая. Он голаздо мягче и быстрее проходит организм.
*** Истерички
Кабинет полон истеричек всех возрастов и полов.
** 09.04.2021
*** Бездели
Чествовали Антона. Получилось неплохо. Торт слишком сладкий. Прикольно поболтали.
*** Крыжечки
Пришли крыжечки для камеры. Надо запилить переходник для ресбери на МТО.
*** Пятничка
Особо ничего не делалось
** 10.04.2021
*** Болтовня
Кооенька сегодня не пошел наверх и целый день болтали без умолку. Это просто адище. Аж заболела голова.
*** Закупки
Немного потратился на всякое китайское авно. Надо еще пересмотреть свои плапы закупок.
** 11.04.2021
*** Конструктор
Порисовал тумбочку, какой-же неудобный этот SW без параметрических размеров и неинтуитивного склеивания поверхностей. Я прямо слышал как скрипят мозги. Надо навертеть БД и ходить API за размерами.
*** ЗП
Еще решил поднять старую табличку с ЗП и наполнить ее данными с 15 года.  
*** Бой
Зачемто поинтересовался, как там успехи у детеныша коллеги. Какая-то медалька есть.
*** Лаборатория
Замутил первую инициализацию проекта Лаборатория по НИР и ОКР в своих увелчениях. В общих чертах туда надо организованно думать всякие поделия для порядочка.
*** Комфорт
Смотрел старые фотографии и оказывается все те бытовые удобства не такие уж и старые, некоторым улучшениям от силы пара лет, а в оолове они как всегда так было. Память ненадежная штука.
** 12.04.2021
*** Референсы
Пересматривал старые картинки, как же много там идеи и референсов для вдохновения. Как-то я костинею в своем развитии
*** Новичек
Притащили нам новенького, вроде адекват, но на передержке. Бесполезная трата времени
*** Совещалово
Что-то каждое наше обсуждение дальнейших действий превращается в плач ярославны
** 13.04.2021
*** Экстрасенс
Поздравил Надю с ДР, она пожаловалась, что в школе воруют деньги, пипец.
*** Преза
Запилил презу по ААА, все остальные нахлебники просто бездельничают.
*** Бумажки
Сходили за бумагой. Качек все стремился таскать руками, пидоры подвязались под работу и слились при первой возможности.
*** Жара
Утром было чуть больше нуля, но днем сильно за 20 - весна
*** Ирония
Может и зря я связался с этими людьми. Я никогда не встречался с иным разумом - все, лишь проекция меня на меня.
*** Твентин Карантино
Придумали нового персанажа, родился в апреле 2020, любит кино, характер нордический
** 14.04.2021
*** Философия
Самый интересный разговор был сегодня - мой монолог про филосовские идеи и образное восприятие мира. Двое отвалились сразСамый интересный разговор был сегодня - мой монолог про филосовские идеи и образное восприятие мира. Двое отвалились сразу, один уснул, и только И пыталась сопротивляться
*** Жара
На улице прям ревльно жарко. Мой мозг начинает плавиться.
** 15.04.2021
*** С такими друзьями и врагов не надо
Они расшатывают мою психику. Помогая выбраться из локального минимума понимания. А еще мнять себ< батьками и могут только булки на деревьях видеть
*** Почки
На некоторых деревьях уже раскрылись почки. Скоро будет лето.
*** Кризис недоверия
Без понимания чужей игры и инструментов этого самого понимания очень тяжко проэцировать этих людей на свой мир.
** 16.04.2021
*** Пешки
ака сегодня пожаловался на меня от имени И и просто скатился на днище, дима недоумевал, почему я раздражен. До этого дима высказывал, что я не даю им сушить мозги, а вот тройничек с антоном вполне для этого годится.
*** Поток
Вечером разыгрался вселенский поток, обещают, что он продлится всю неделю
*** Анализируй это
Излил душу Илье, как тяжело живется на свете изгоем
*** Мисскомуникация
Попытался излить душу на бумагу, но полная фигня получается
*** Кастрюллер
Коленька фигачит в солиде квартиру без обучения и получается вполне сносно.
** 17.04.2021
*** После каждой бури светит Солнце
Вчера был ливень. Сегодня солнце. Вчера была травля. Сегодня "Мне комфортно с вами общаться" и дружеские шуточки. Всю ночь придумывал гадости и мерзкие вопросы, но ничего этого не нужно.
** 18.04.2021
*** OSM без меня
Зашел на карты и там никакого прогресса. Последние пару тройку дней возникает непреодолимое желание писать и изменять мир (после изливания мировосприятия И и ее совета, что такие сложные мысои надо писать, т.к. они всеравно ничего не понимает)
*** Веневка
Димка поменял колеса и в +10оС они гремят как сволочи. Это  подозрительный звук мы поехали тестръировать в сторону по веневке - ужасно извилистая рельефная дорога по деревушкам и виды так себе.
*** Крафт
Смастерил из бумаги и скотча окуляр для обьектива. Потом начал мастерить примочку для камеры, но осложнилось все тем, что доступ к камере через удаленный стол не так прост. Сел ноут и разболелась голова. Но это новый виток в использовании железа.
*** Пробуждение
На покатушках подзамерз, погода скатывается и меня вырубило. Мама позвонила в семи и я до конца разговора не мог сообразить какой сегодня день, думал что уже семь утра и надо бежать на работу и я проспал
** 19.04.2021
*** Туча
Льет дождь. Промочил обувь. Без шапки холодно. И ходит мрачная и злая. 
*** Коработинг
Сидели с Димой писали текстовку, он вообще никуда не годится по сложному мышлению, неусидчивый и начинает брюзжать. 
*** Скрипы и хрипы
Подтянул у всех стулья и смазал Илюшин стул. Надо отрегулировать его скрипучесть. Рома пересел на место болотниковой и слегка прихуел. 
*** Завалы
Попросили сходить на аттестацию пораньше. Накидали еще бумаг. Никто не хочет работать. Руководстово измельчало.
** 20.04.2021
*** Шапка
В мой гардероб вернулась шапка и перчатки. Весна кудато делась и дождь идет четвертый день.
*** Падаван
Коленька впитывает мою пропаганду. Попросил подтянуть его в екселе. Умничка.
*** Имбицылы
Ребята просто все глубже проваливаются в развитии
*** Пузырь
А я все чаще замечаю отсутствие какого либо развития в мире. Все идеи - жалкое подобие идей прошлого. Плохо жить в кризис
*** Пашка
И проходя назвала меня Пашкой (хороший знак) но напряжение все еще чувствуется (может это и самолюбование)
*** Начальник года
Никто не хочет работать, верчу эту ветуацию как могу. Уже сил нет. Пора их заменять скриптами. Если они не хотят принимать решения, то за них их примут другие, а ответственность никуда не девается.
** 21.04.2021
*** Цейтнота
Расписания накладываются одно на другое. На текущий момент вроде все разгрузилось, но что-то груженое все.
*** Война Афины
И лайкнула фоточку меня присланную от Д, с другой стороны она вопила в кулуарах в альянсе, что терпеть меня не может. Надо разобраться в тактике и стратегии ведения войны с психологически неустойчивым противником. И еще эти сюси-пуси с антоном меня удручают
*** Нежелательные встречи
Пони пересекся на светофоре и предьявил, что я медленно хожу - ну и шел бы отсюда побыстрее
*** Сяськи масяськи
полудара лабызается с своим полудурком. Стану ли когда нибудь я так нужен комуто, когда не человев а тряпка помоишная превращается в глазах этих созданий самым единственным человеком?
** 22.04.2021
*** Нехачуха
Кн задолбал, не хочет работать. Я его тыкаю носом в его прямые абязанности, он убегает переставлять машину
*** Нужник
И пристала ко мне с планами и стояла над душей, пока я их ей не нашел, очень забавная ситуация
** 23.04.2021
*** Совещалова
Пошел утром узнать один вопрос, а на меня навешали тонны поручений, которые я успешно несделал
*** Батутошная
Тут еще прилетело от Ильича распарсить табличку, занимался ей полдня
*** Показуха
ААА прошло отвратительно с цирком с конями, и закончилось еще более странно намеком на трансфер
*** Обед
Покормили Диму в столовке, он отметил как хорошую столовку.
*** Отбросы
51 что то вообще никуда не гадится, андрей мудак, всякие имбицылы лезут во власть. Отдали комп Эда Саше и оборвали все цепочки
** 24.04.2021
*** Ух
Весь рабдень меня терзала мысль развить слух, чтобы понимать, что происходит вокруг. Стал слышать часы в другом конце комнаты. Может технологию поставить на эту службу.
*** Циклоп
Утром зарядил мокрый снег, до обеда не прекращаясь лил дождь. Когда вышел с работы - светило солнце. По дороге кружили тучи сквозь солнце циклопических размеров. В районе уже лупанул снежище. Температура с 7 упала до 2 за 10 минут. Грибной град. Когда показывалось солнце - все начинало парить клубами и это выглядит очень красиво на воне черных туч и солнца.
*** Виноград
Посадили за беседкой виноград. А его засыпало снегом.
*** Инвитро
Что то большой процент брака в инкубаторе. В тех, которые дошли до текущей стадии, даже видно как бьется сердце, выглядит пугающе Надо что-то додумать получше - постоянную циркуляцию тепловых потоков и регулировку влажности и как-то разделять этажи
** 25.04.2021
*** Факторево
Димка поставил мне игру. Надо попробовать.
*** Стратегия и планирование
Самое сильное из моего сегодняшнего ютубчика это были Веда, Школьник и Переслегин вунисон рассказывающие одно и тоже. И еще про хакинг прикольная статья. Надо опять учиться и создавать.
*** Подстригся
Стараюсь стричься раз в три недели. Стригу бороду раз в неделю. Как же это удобно, так изредко заботиться о своей голове. А я все чаще замечаю, что волос на ней становится все меньше. У Димки в принцыпе тот же крой, только прическа другая.
** 26.04.2021
*** Разборки
С Димой смотрели, есть ли у принтеров сердце.
*** Отказники
Послан делать его работу Андрея, он теперь обижается.
*** Солнцеснег
Погода вертится каждые 5 минут. Но рак то погода сегодня хорошая
*** Пост
Забрал с почты 6 пакетов. Винтики для дрона, штативную голову и мелочи. Надо что то собирать
** 27.04.2021
*** Зеленое на белом
Ночной снегопад породил чудную картинку. Из по десятка сантиметров снега торчали зеленые трави и можно было запечатлить чудные картинки, а люди фотали толко поваленые ветки и оборванные трамвайные провода. На работу мы решили пойти пешком.
*** Надоеда
Опять начал задвигать И всякую дичь. Вот уж воистину она инсталировала в меня недокументированные приложения. Надо бороться с эоим.
*** Груша
Купил грушу и она волшебно-вкусная
** 28.04.2021
*** Панорама
Запилил шикарную панораму центра с колеса. Аж самому понравилось. Завтра посмотрю реакцию. Но мое творчество в первую очередь радует меня
*** Два пакета травы
Решил купить газон. Нашел только в орле. Девочка на связи туговата. За сегодня не успел договорится.
** 29.04.2021
*** Вау-эффект
Делай добро и убегай. Ребята оценили новую панорамку. Выглядит она гораздо интереснее.
*** Аттестация
Прошло все нормально. Все что просил мне дали. 
*** Падаван
И опять упомянула, что ее детенышь подался в азы программирования. Мне прям уже самому стало интересно, что можно вылепить из этих падаванов.
*** Сбор
Собрал вещи. Опять нихрена не входит в сумку. Все суматошно и неспланировано. Больше всего беспокоит перспектива торчать в автобусе сутки.
** 30.04.2021
*** Поехали
Быстро переписал бумажку на выходи и в 12 вышел с работы. На удивление собрались за 7 минут и уже в 12:07 отправились в путь. Погода была не очень. Прямо перед мостом пошел дожь. Ночь в автобусе это крейне неудобнове времяпрепровождение. Но еще более неудобное времяпрепровождение - это суткуи в автобусе.
*** Трамвай
Утром добирались до работы на трамвае. Это просто тихий ужас какаой-то. Народущи битком. Все талкаются. Все ненавидят друг друга. Опять Сплав делает весь трафик. Сколько же там работает человек. А буквально пару лет было загнивающее заведение. 
*** Зеленеет
По мере продвижения на юг трава становилась зеленее и деревья все пушистее.  
* May
** 01.05.2021
*** Безсна
Ночь в автобусе это тяжело. 
*** Приморские деревушки
Не приходя в гостиницу пошли шляться по севастополю. Ну в общем это распиаренный новомосковск. Еще и обремененный балками и сложным рельефом. 
** 02.05.2021
*** Восходители
Понесло нас на Чуфут-Кале. Воспоминания 20 летнего меня немного другие. Легкая проглка, прикольно. Ты уже по другому воспринимаешь действительность. Виды стали еще прекраснее. 
*** Полящий
Очень повезло с погодой. Правда к концу похода макушка обгорела и кожа побаливала. Зато я получил прекрасный южный загар, а Димка немного обгорел.  
*** Гулящий
А после всего этого меня понесло гулять по городу. Истинная цель была купить вина. Но и прогуляться тоже. Я не видел бомжей уже очень давно. А тут они на каждом шагу. Полно заряженной молодежи. Не самый благоприятный город. Потом меня понесло к памятнику солдату и моряку, а там молодежная тусовка. Фотки заката получились не с самого удачного ракурса. Вернулся в гостиницу в 9 часов. Недосып. 
** 03.04.2021
*** Канатка
Поехали на Ай Петри. Канатка прикольная. Вид с горы просто восхетительный. Прогулка удалась на славу. Шикарные виды. Шикарная природа. Очереди и чурки.  Вот эти прогулки для меня. Еще понравилось Ласпи, надо будет когда нибудь туда забраться. 
*** Винбазар
Купил еще винишка. Экскурсовод рассказала, какие вина надо покупать только после этого всего. Оказывается взял два белых и два красных. Народ набирал коробками. 
*** Ялта
Довольно унылый туристический город. Прошлись по набережной и потом тупо сидели на лавочке и любовались морем. 
*** Ботаны
Под конец этого всего нас понесло в Никитинский ботанический сад. Там были деревья в основном. 
*** Дождь
Как только последний человек зашел в автобус для отправления, на улице пошел дождь. Кончились теплые деньки в Крыму. 
** 04.04.2021
*** Дорога
Ехали.
** 05.04.2021
*** Сушка
Проснулся и от этого обезвоживания вся кожа стянулась. Взвесился на 85.5 кг. 
*** Пластик
Зашли в Декатлон купить кепку, а это лютый пластик. решил померять зеленую куртку, а это тупо пластиковый пакет. Одежда из говна и палок. 
*** Отчет
Поехали домой. Показали фоточки. Выпили вино - вполне себе годное. Дальше все отвалились спат.
*** Трава
Мама купила в ларьке траву по той-же цене что и я в интренете, только без добставки и мгновенно, а у меня еще не понятно, что происходит. Вот она чудо логистика интернета. 
** 06.04.2021
*** Забор
Поставили один пролет забора перед домом с северной стороны
*** Непонимание
Папа вообще не понимает как общаться. Упрется в свою гениальную идею. Все кругом дураки, один он молодец.
** 07.05.2021
*** Заборизация
Доделали забор, выглядит так себе. Но лучше чем было.
*** Заваленка
Переложил дрова. Стало еще теснее.
*** Распашка
Папа договаривался распахать огород, но мужик продал трактор. Пришлось быстро распахать минитрактором в фрезами мужиком который варил варота
*** Старлинки
Вышел на улицу вечером, а там паровозик старлинков. Будущее здесь
** 08.05.2021
*** Дожди
Погода пошла по одному месту. До обеда куковали. Решили поехать в деревню. Купили ребятам кораблик и гостинцов. Посидели, сходили на кладбище, поели, попили вина, поболтали. Хорошо.
** 09.05.2021
*** Сетки
Натягивали с папой сетки для кур. Он каким то чудом принял концепцию газона. Надо разбирать углы.
*** Шашлык
Уже на закате сел жарить шашлык. Волшнбный закат с треском дров и жаром от углей. Шашлычек получился сочным и поджаристым.
*** Корпус
Димка запилил корпус БП. Получилось очень хорошо. Я тоже поучаствовал в этом процессе. 
** 10.05.2021
*** Солнце
Сегодня прекрасная погода. Светит солнце и уже можно прогуляться бнз шапки. Только очень ветренно. Красивый закат и звезды.
*** Мясо
Пошел купить мясо, но лавка уже закрыта. В кландайке открылся новый мясной магазинчик. Купил там вырезку на кости и зажарил ее. Получилось просто волшебно по картинке.
*** Стекла
Когда решил запечатлеть кусок мяса, понял, что надо преобретать человечьи стекла с автофокусом и фиафрагмой. Руками следить за тысячей параметров не удобно. А еще мне нужна гмстагармма и монитор на камеру.
** 11.05.2021
*** Счастое
Пошел на работу без часов, непривычно, но постоянный гнет спал.
*** На работу
Димка пошел на больничный, а я пешком на работу. Все сидят и не понимают, что делать. И я. День кое как прошел. Показал фоточки. Немного подразобрались с мотивацией. К вечеру стало жарко в плаще.
*** Камера
Пришла маленькая камера - очень неплохо. Надо с ней разобраться.
*** Трава
Еще пришла трава - просто отсывали в пакете и завязали пломбой. Больше не не=адо покупать всякое в интернете.
** 12.05.2021
*** Дождь
Погода испортилась
*** Не сладко
Купил вафли и сладости и не зашло совсем. Это нихрена не вкусно.
** 13.05.2021
*** Расчеты
Практически за день не происходило ничего знаменательного. Беготня и бумажки. Хотел почитать, но не выкраил ни минуты. Считал.
** 14.05.2021
*** Рань
Вышел из дома пораньше и напугал всех на работе.
*** Цукаты
Ребятам надоели сладкие цукаты и их женщины вручили им сушеные овощи, я попробовал что-то типа баклажана и гриб, очень странные ощущения.
*** Тишина
Половина народу нет на работе и я немного почитал.
*** Мокрые штанишки
Вышел с работы и начинался мелкий дождь, очень красиво бил по асфальту. На полпути уже заливал ливнище. Пока дошел - он кончился
*** Цветущий сад
Дома, по сравнению с прошлой неделей, распустились цветочки, зеленые деревья, густая трава. Красота. 
** 15.05.2021
*** Перепевы
В четыре часа пнекрасно все в саду. Резко распустилась вишня. Птички поют свои трели. Начинается рассвет. Прекрамно
*** Рынок
Пошли на рынок. Там ничего особо не изменилось.
*** Посадки
Посадили картошку. Погода ухудшалась и мы стали сажать быстрее. Когда закончили - жарило солнце. Я немного подгорел. Посадили лук и цветы и кабачки. Закончили почти все срочное.
*** Шашлык
Пошел жарить шашлые. Что-то он у меня не дожарился. 
*** Месяц
Очень красивое звездное небо. Молодой месяц закатился за деревья. МКС. Лебедь выкатился из-за горизонта.
** 16.05.2021
*** Аквариум
Спал сегодня в аквариуме. Не прям чтобы очень круто.
*** Жара
28 градусов. Началась печка. На улицу неохота выходить. Все зеленеет буйным цветом. Вишня цветет. Тюльпаны отцветают за 2 дня.
*** Вело Катя
Приехали в Тулу и я решил раскупорить вплосипед. Поехал к Кате забрать на профилактику ноут. Слегка неудобно вновь осваивать велосипед. За зимо я совсем ослаб. Надо держать себя в форме. Прокатился до Кати и обратно. Велосипед это кайф.
*** Перепорядок
Посмотрел видосики и стал собираться к понедельнику. На всякие мелочи потратилась уйма времени.
*** Монитор
Перевез из дома старый моник для малины. Пока катался, Димка пристроил его для компа. Надо разбираться.
** 17.05.2021
*** Лето
Переоделся в светлое. Натянкл рубашку без рукавов. Жара. Хорошо.
*** Говнокод
Сижу, верстаю модель управления. Пишу говнокод. С одной стороны он мне не нравится, а с другой - он работает.
** 18.05.2021
*** Профком
Было собрание профкома отделения, переизбрали председатели и дособрали меня в члены
*** Прохор
Смотрю мужика втирающего про планирование и вникаю
*** Разрешение
Наконец настроил разрешение на малине. Будем продолжать
*** Ноут
Катя приехала забрать ноут и я пошел ей его передать. Вышел в 9 часов и на улице легкая прохлада, режимный свет и красивая девченка меня ждет - красота.
** 19.05.2021
*** Моделирование
Сижу моделю версталище и балансировщик. Идет туго. Решил разобраться в бумагах - стало только хуже.
** 20.05.2021
*** Навясчивость
Позвонила ТетьВера и стала втюхивать кредит на квартиру и втирать всякую дичь. Весь вечер был испорчен.
*** Упаковка
Пытался завернуть подарок И, а он все-равно булькает. Весь изнервничал.
*** В темном
По случаю плохой погоды достал темный костюм, а его надо заменить или хотя бы постиратл. Неприглядный вид.
** 21.05.2021
*** Винишко
Подарил И винишко, она была довольна. Сказала, что очень вкусное.
*** Балансировщик
Придумал как считать общую загрузку и уперся в следующий параметр оптимизации
*** Киборг
По улице ходят люди с киберногами - булущее наступило
*** Обучение
Димка взялся наставлять меня по Факторио и я закончил обучение в третем часу ночи
** 22.05.2021
*** Магазинчики
Купили ботинки Димке и мелочи для дома.
*** Газон
Весь двор зарос ромашкой. Мама зачастила шашлыком. Шашлык получиося зажаренным.
** 23.05.2021
*** Михалково
Папа опять парил перевозку мешков с картошкой для тетьтани и Димка обоснованно был недоволен такой ситуацией.
** 24.05.2021
*** Женя
Женя проставлялся за ДР. 
*** Факторево
Проиграл пару часов. Затягивающая штука.
*** Винты
Возникла проблема с файловым хранилищем и пятнашка встала в самоблокировку.
** 25.05.2021
*** Завалы
Сегодня у начальства были переодические разборы бумаг и нашлись пачки срочных работ к февралю
** 26.05.2021
*** Помощ
Попросил помощ у специально обученных женщин и они помогли. Портянка собирается гораздо интереснее.
*** Вело 25
Скатался в центр, парк и политех. Человечки бродят туда сюда. Надо перебираться ближе к центру или полюднее.
** 27.05.2021
*** R
Поставил на малинке R, и наверное студию туда не поставить. Но оказывается есть облако для R и можно попробовать фигачить там. Но так то конечно нужна интел виртуалочка, а лучше нормальный комп.
** 28.05.2021
*** Недосып
Что то рубит сегодня целый день, может из за смены погоды. Гроза и ливни перемежаются солнцем
*** Ферма
Собрал раму дрона. Почему я все время это откладывал? Получилось громоздко и неуклюже.
** 29.05.2021
*** Триммер
Заехали к тетьвере за тримером. Попробовали его дома. Вполне пригодная штука. Обкосил сосны и забор, Димка обкосил ворота и говорит, что надо газон косить тоже. 
*** Аллюминий
Опробовали метод пайка аллюминия горелкой, вполне годная технология. Запояли все пробитые корцы.
** 30.05.2021
*** Холод
Еще вчера погода ухудшилась. Не прекращаясь моросит дождь. Сырость и холод.
*** Мясорубка
Мама сама исподобилась использовать электромясорубку против ручной. Очень удобная штука.
** 31.05.2021
*** Смена власти
Махнулись начальники местами, в работе ничего не поменялось.
*** Заявка
Подал заявку на отпуск
* Jun
** 01.06.2021
*** Некрофил
Экснач поимел кучу освободившегося времени и теперь оживляет старые проекты. А делать все это мне.
** 02.06.2021
*** Размышление
День ничегонепроисхождения и размышления. И отвалилась в отпуск и оставила после себя яблоко и кризис доверия.
** 03.06.2021
*** Покой
Без И на работе мне спокойно и работается. Спала пелина и появилась четкость бытия
*** Понижение
Кн как-то странно реагирует на то, что я  подписываю бумаги у Ч. Ака предлагает мне сдаться в ррансформаторную. Дима вернулся, а у меня только призрение к его повадкам. Крушение бытия.
*** Лиза
Экоженщины вообще недалекие и не справляются с работой. Помог с организацией. Аня выслуживается перед Ч просто пипец. Что вообще происходит.
** 04.06.2021
*** Маша и Медведь
Пришел на работу, Дима сидит у меня на столе, разложил свои сумки и накидал пакетов от пиражков. Шелб.
** 05.06.2021
*** Косьба
Сьездили на кладбище, покосили траву. Папа решил расширить ограду - это пипец как стремно. Сьездили в Осиново.
*** Газон
Обкосил машиноместо. Димка виноватит меня, мол не так кошу.
** 06.06.2021
*** Погода
Когда поехали в Тулу, погода менялась десяток раз с плохой на вообще ничего не видно.
** 07.06.2021
*** Компы
Уходит на пенсию коллега и я поучаствовал в дележке компов. Очень скучные дела.
*** Передача
Сдал отчет по работе одним из первых. Теперь от меня полгода ничего никто не требует.
*** Откосил
Пришел с ралоты и решил заскочить за телефоном. Только поднялся и вкатил дождина. Я прошел сегодня между каплями.
** 08.06.2021
*** Ишрун
Засиделся за факторивом до полуночи
*** Данные
Работа в профкоме уже требует от меня каких-то данных
** 09.06.2021
*** Баланс
Весь день считал человечков
*** Залипалово
А потом строил заводы
*** Туча
И по дороге домой попал под дождь
** 10.06.2021
*** Маята
На работе уперся в этот балансировщик и ничего никуда не движется
*** Искуситель
Димка пошнл посмотреть что я понастроил и я опять проиграл до полуночи
** 11.06.2021
*** Тишина
Практически никого из буйных нет. Аня прискакала в обед и всех разбудила. Весь 7 свалился в заразу.
*** Расслабон
Вот и начинается мой отпуск
** 12.06.2021
*** Изменение планов
Утром немного прибрался, помыл чайник, и выяснилось, что мы едем домой. На дороге тысячи народищу. Тополиный пух висит в воздухе как кисель. Дома прям к нашему приезду пошел доджь и мы весь вечер смотрели сериал.
** 13.06.2021
*** Свины
С ранья понесло нас в бгр за поросями. 
*** Газон
Скосил весь газон под чисто и вьезд. Надеюсь что-нибудь выростит.
*** Огород
Прополол с мамой огород. Слушал параллельно книгу.
*** Наблюдение
Примастерил мто на штатитив. Получилось неплохо. надо понаблюдать луну и узнать поля зрения. А вечером рилетела довольно зрелищная гроза.
** 14.06.2021
*** Кухня
Приготовил обед на маминой кухне - все не так, все непривычно, непонятно, где что лежит.
*** Тула
Опять уехали в Тулу. Залипали за компами.
** 15.06.2021
*** Анализы
Пошел в диагностику, врачиха уставшая. Сказала катать на веле и ходить в бассейн. Прописала еще таблеток.
*** Ливень
Пошел из диагностики гулять. Только надвигающаяся буря загнала меня домой. Автобусы - гавно. На улице жарко. Гулять не интересно
** 16.06.2021
*** Вело 32
Поехал кататься по городу. Погода отличная, сгорели руки. Нашел пару новых мест. Чем больше я открываю, тем обыденнее становится город.
*** Недолет
Посмотрел документацию к полетному контроллеру, промазал с управлением по вайфай. Но надо всего лишь дособрать дрон, все больше он мне нужен
*** Камера
Подключил реберикам, что-то картинка так себе. Надо купить других стекол.
*** Приглос
Прилетело приглашение от Коли на свадьбу, конечно же я пойду.
** 17.06.2021
*** Ревизия
Немного разобрался в пакетете с пакетами и выкинул 4 пакета с мусором. Надо еще причесать.
*** Керчь
Написал И, как ее там не залило ли. А она уже дома
*** Луна
Выставил трубу с окуляром и это офигительно интересно
*** Вино
Открыли мускат красного камня и это слишком притерно сладкий кампотик, но по ногам дает.
*** Рассказы
Решил дождаться Юпитера и воткнул в уши Азимова
*** Планета
В первом часу пошел смотреть планеты. Юпитер со спутниками отчетливым кружочком, а в Сатерне планета отделяется от диска. Смотрел до полвтрого. Очень сложно с наведением. Надо деоать моторизированную систему.
** 18.06.2021
*** Стены
Сняли панель в углу кухни. Крысы сожрали там все. Решили заделывать кетамзитом. Возился с обрешеткой.
*** Шато Шведо
На ужин мама достала свое вино. Вполне себе годное. Лучше вчерашнего слащавого.
*** Косари
Все утро жужали и покосили дт деревьев по дороге. По мне лучше бы они ее оставили как есть.
** 19.06.2021
*** Обрешетка
Весь день крепили обрешетку. Под вечер от жары стал реально тупить
** 20.06.2021
*** Все переделать
Решели переделать весь утиплитель и сняли панели. Там дохлые крысы. Вонища. Надо все переделывать
*** Проект
Нарисовал проект трубопровода.
*** Огород
Поехали тяпать картошку в поле
** 21.06.2021
*** Расчеты
С утра начал перерисовывать схемы. В итоге ничего не сошлось и все деоали по месту.
*** Тула
Поехали в Тулу за трубами. Димка вымотался, я тоже подустал. На улице невероятно жарко. В городе вообще невыносимо.
*** Волшебная луна
Ромашки по дорожкам в свете луны - волшебно.
** 22.06.2021
*** Жара
Прямо каждое движение и ты перегреваешься
*** Обрешетка
Даже недоделали вертикальную обрешетку. Очень жарко. Еще завтра целый день делать.
** 23.06.2021
*** Усиление
Делали усиление для батареи пол дня. Доделали вертикали и окно
** 24.06.2021
*** Разборка
Разобрали ванную комнату и во дворе комнату для зерна. И немного на подвале.
** 25.06.2021
*** Разборка
Димка разобрал два старинных телевизора, а я выкинул корпуса. Стало просторнее на кубометр.
*** Шкафчики
Потеряли пакетики для посадки винограда и мне пришла в голову идея сделать из текщей кухни кладово шкафовую
*** Жара
Все жарче и жарче. Все ждали грозу, а она прошла рядом.
** 26.06.2021
*** Жара
Очень жарко. В обед все отвалились спать.
*** Ныряльщик
Так жарко, что я пару раз нырял в ванную. Так класно ощущать архимедову силу. Надо ходить в бассейн.
*** Вокзал
Сходил посмотреть вокзал. Просто покрасили и разобрали туалет. Стало покрасивее.
*** Дождь
Вечером наконец дождались дождя. Тот был непродолжительный. Сфотал радугу на 500. Не влезает
** 27.06.2021
*** Чтение
В невероятную жару читал и спал
*** Решетка
Доделали обрешетку, невероятно жарко
** 28.06.2021
*** Сосунки
Рано утром какие-то имбицылы включили музыку в машине, наверное провожали кого-то в военкомат, но чего я не ожидал, так это матерных частушек в 2021 году
*** Финита
Димка уехал в Тулу. Теперь отпуск буду делать один
*** Засыпка
Доделали половину стены и я засыпал керамзит
** 29.06.2021
*** Нарезка
В ожиночестве нарезал верхний ряд плит. Мама помогала. Потом весь день убил на засыпание первой секции.
*** Сток
Сделал дождевой слив над дверью и получилось так класно, что теперь надо переделать тот, что уже имеется. Испытания не заставили себя джать. Ливень разрозился, пока я бегал в магазин.
*** Обратный пылесос
Переделал пылесос в закидывателт камней пд обшивку. Пыли наглотался, зато дело пошлот быстрее.
** 30.06.2021
*** Бгр
Поезхали с мамой в Бгр. Купил богоугодных саморезов, погуляли по парку. Реально очень круто. Сделали красиво. Дощли с мамой до прудов.
*** Аки кони
Пропахали огород. Устал. Жарко.
* Jul
** 01.07.2021
*** Труд
Весь день засыпал керамзит
*** Машка
Ходил в хозмаг за керамзитом и по дороге слепило солнце и со мной кто-то поздаровался "Привет Пашка" я конечно ответил, но кто это бы, я не понял, возможно Машка Иванова из А
** 02.07.2021
*** Рассвет
Утром встал и встретил туман и пение птиц. Потом целый дено спали.
*** Димка
Приехал сегодня. Хорошо.
*** Квартира
Сходил на квартиру. Как хорошо, что мы сделали ремонт в ванной.
** 03.07.2011
*** Швы
Залепили шпатлевкой швы. 
** 04.07.2021
*** Ограда
Поехали наращиват метры на ограду. Убили пол дня.
*** Ванная
Открутил элементы у ванной. Крысы сделали себе удобный лаз на бочки. В других местах вроде нетронуто
*** Шпатлевка
Решил зашпатлевать стены. Получилось так себе
** 05.07.2021

