* Jan
** 01.01.2021 Пт
*** Ледяные цветы
Абсолютно все зашито в ледяно понцирь. Туман осаждает на деревьях и цветах иней и они превращаются в ледяные цветы. Каждый раз выходя из дома попадаешь в зимнюю сказку.  
*** Сериальчики
Занимали день сегодня безудержным просмотром сериалов. Один безинтереснее другого. В это время каждый занимался своим делом. Мама разгадывала сканворды, Димка играл в Факторио, я читал книжку. Папа спал.  
*** Реклама
От безделья понесло меня в Ютуб на телефоне. О ужас. Я узрел рекламу. Это отвратительная мерзость. Как люди вообще сидят не в Опере. Блаженные в своем неведении люди смотрят ютуб с этой рекламой. Я то думал, что мерзость, это когда ведущие непосредственно рекламят свякие игрушки и голосом рассказывают как они там что-то делают, но это было лишь вершиной айсберга. Ютуб сам суют каждые 5 минут левую рекламу - это ужасно. Жду недождусь, когда вернусь к просмотру ютубчика в Опере.  
*** План А
Начал читать "Республика Волмарт" и это вызвало у меня прямые асоциации для лого одной из моих групп. По приезду к нормальному компу надо будет перерисовать в нормальных скруглениямх и цеветах. Но пока пятилучевая звездочка (мир без звездочек) и градиент перехода (как в загрузке (только я ошибся и нарисовал градиент в другую сторону). Символизируют загрузку новой SocOS.  
** 02.01.2021 Сб
*** Отвертка
Просятил Димук, что в Никоновских объективах морочкик в фотике и крутится там отвертка. Почему они такие дорогие, мы не придумали.  
*** Снежки
Димка пошел приклеивать градусник и зарядил снежки в рабицу. Получились прикольные дыры в ледяном панцире сетки. Выглядело более чем эффектно.  
*** Чтиво
Практически весь день придавался чтению Волмарта. Не Стивенсон конечно, но годнота.  
*** Сериальчик
Посмотрели Звездный путь. Кругом сплошная политкоректота, но с фантастической точки зрения никакой.  
** 03.01.2021 Вс
*** Арома
Обновил еще один балон масляной мяты, разлил балон спиртовой мяты и балон дегтя. Может показаться странным, но это работает (пока не доказано обратное).  
*** Горизонт
Когда поехали, были прикольные виды с снежными тучами и самосветящимся горизонтом. Четкое разделение неба и земли застовило задуматься "как давно я вообще видел горизонт". Деревья в ледяных панцирях и грязная дорога.  
*** Непрядва
Заехали за Катей. Там бабская суета и Леша жарит шашлык. Катя набрала тяжеленную сумку. Степка уже указывает, что надо закрыть дверь. Все хорошо. Мама просила сфотать речку.  
*** Тула
Приехали. Тут грязища. Скука скучная и единстенное развлечение - компьютер. Надо переводить этот инструмент из разряда развлечений в дело.  
*** Дугин
Это прекрасно. Посмотрел НГ обращение Дугина на Авроре и просто катался по полу от смеха. Один из немногих русских философов современности цитирует мемасики и призывает читать классиков. Он шикарен.  
** 04.01.2021 Пн
*** Отпросилась
Погда я еще спал, но уже успел заварить чаек и залезть в ВК, мне написала И, и сообщила, что не придет сегодня, и ей слишком лениво. Я что-то прям расстроился и решил пойти в спортивной одежде и вообще отмести любые приличия и деградировать. Я удручен.  
*** Работа
Пропуск сразу не сработал и решил пропустить меня только с третей попытки. Предъявил на входе банан. Работа внеурочное время так себе. Мой приказ так никто не подписал. С бездельниками надо что-то делать. Серегин пришел ко мне в надежде, что я сегодня не работаю. Ходили толпы бездельников рассказать свою душещипательную историю про новый год.  
*** Семейные ценности
Часть команды расскзал, как сделал предложение своей девушке (с которой 9 лет), Илья - про то, что пора бы и к ней съездить на НГ. Макс - про то, что пора завести детеныша и что у него что-то не получается, Алексей - что он включил перфоратор, Аня - что бухала и бухала. Что-то мне эти разговоры не нравятся.  
*** Чтение
Нашел там книжку с ноута. Уж очень это неудобно. А еще толпы болтающих бездельников. Прочитал только пятую часть. К обеду от бездвиженного сидения уже стало все затекать.  
*** Макадамия
Макс посоветовал орехи. Бербраер их тоже нахвалилва. Купил попробовать. Первый - приольно - новый вкус и приятный запах. После третьего это стало просто неинтересно. Взвесили вес ядрышка к скорлупке и получилось чистая цена 5000 за кило - наркота походу дешевле. Мне не понравилось.  
*** Перехват
Шел с работы. Поболтал с мамой. Смотрю - машина меня дожидается. По номерам что-то знакомое - ну я и сел. Первый раз мы с Димкой пересеклись.  
*** Вибрация
Сходил в магазин, а Димка все еще на парковке с открытым багажником и счастливым (катарсис) лицом. Оторвана панель у багажника и там проводок, который скорее всего трется. Он нашел эту сволочь. Счастливый перетянул все паралонками. Теперь осталось проверить.  
*** Тыква раздора
Приготовил овощное рагу и кинул туда тыкву. Димка стал мрачнее тучи. Ну да, что-то не очень прикольный рецепт.  
** 05.01.2021 Вт
*** Обыденность
И пришла на работу. Антон пришел на работу. Опять эти их семейные ссоры. Прям градус интереса к ней сразу поубавился. Все уже было.  
*** Ветер перемен
Второй раз проскочил слух, что Кн смещают и Ч бедет за него. От этого у меня прям прошла досада от бессилия что-то делать. Все наработки коту под хвост. Надо с этим что-то делать.  
*** Календарик
Запилил И календарик с зубренком. Но мне не нравится на сегодняшний день верстка. Надо что-то думать друге. Вышел распечатать, И разговаривала по телефону у принтера, попросил ее подождать и болтали пока печатается, что-то проскочила боль в груби, было бы не очень красиво грохнуться в такой красивый момент.
*** Финвиз
Скачал нормальные .csv финтрат. Данные гораздо интереснее, но не полные. А еще посмотрел в ЛК траты по дням и офигел слегка. В день по 500-1500. Всего за 2020 250кр затратных. 
*** Преподство
Что-то на волне вчерашних разговоров про семейственность у меня все чаще проявляется непреодолимое желание кого-то учить и властвовать безраздельно. Сегодня посмотрел еще Дугина и это просто прикольно - под старость надо переходить в преподство. Чувак шарит и еще и в теме. Аж подписался на него в ВК.  
** 06.01.2021 Ср
*** Головомойка
Устроили головомойку Ане, сколько желчи и неприязни вызывает эта девочка.  
*** День живота
До этого брал с собой в обед бананы. Сейчас взял картошечку с красной рыбкой. Потом дома набился живот. 
*** Слухи
Озвучил слух по поводу кадровых перестоновок и прям за 15 минут волна женской слуховой сети развеяла слух переведя его в раздел слухов.  
*** Сериальчик
Наткнулся на старинный британский сериал, за вечер осилил 2 сезона. Закончил смотреть в час ночи. Нихрена не выспался. Но сериальчик прикольный.  
*** Чтиво
Дочитал Волмарт. Полнейшая хрень. Хотел поискать что-то еще в чтиво, но сериальчик пересилил меня.  
*** Пенопласт
Димка решил, что звук в комнате проводит дверь. Накрутил на нее пенопласт и думает, что это сработало.  
*** Пароль
Пол дня И и Антон шептались. Решил присоединится к ним. Там просто светские разговоры. Но уровень их общения похож на старую семейную пару. Этот выпендреж Антона и усипуси И. И знает его пароль в телефоне (0356) и они пользуются общими ресурсами. Вместе делят еду. Вместе куда-то гуляют на долго. Меня это бесит.  
*** 50 мм
Смотрел старые семейные фотографии, снятой еще на "смену" (40мм) и прям совершенно необычный эффект всего близкого. Все крупно и детально. Надо быстрее покупать полтинник и пробовать что-то творить
** 07.01.2021 Чт
*** Мойка
Поехали домой. Дорога отвратительная. Димка решил помыть машину. Пол дороги брехал и заставлял меня найти в неработающем интернете, есть ли в Волове мойка. Такой чистой машина не была с конвеера.  
*** Головняк
Что-то меня вырубило после дороги и теперь болит голова.
*** Белое
Такой красивый иней. Рабица и деревья. Все вокруг.
** 08.01.2021 Пт
*** Когнитивное невосприятие
Смотрели "Экспансию" и прям несоответствие брасаются в глаза и теранят мой мозг. В книге более сильные сюжетные повороты и совершенно иные персонажи. В сериале все топорненько подогнано для туповытых зрителей и сокращенное время повествования.  
*** Головняк
Болит голова весь день. Мама сказала, что у нее тоже - у меня прям сразу отпустило.  
** 09.01.2021 Сб
*** Сериальчики
Целый день гоняли сериальчики. То один, то другой. Что-то такое себе времяпрепровождение. За эти 10 дней практически потратил весь 11 ГБ трафик в интернете, впервые за все время пользования телефоном.  
*** Холодная оттепель
Весь день ждали -30оС, а на улице лишь капало с крышь и слоился туман.  
** 10.01.2021 Вс
*** Тула
Поехали в Тулу. Вся машина обледенела коркой. Дворники не работают как надо и всю дорогу я смотрел на мутное пятно перед собой и белый горизонт в боковом. В Туле вообще грязища. 
*** Кино
Посмотрел "Неадекватные люди 2" и прям норм. Первый поинтереснее, а тут девка сама дура. А психолог героически всех спас, хоть и не так как мог. Задуматься заставляет.  
** 11.01.2021 Пн
*** Бездник
Илья проставился за ДР. Поели пирожек. Очень по семейному. Там на верху только и разговоров, что о COVID. Тортики вкусные, но никакого ощущения праздника.  
*** Свободное дыхание
Забыл натянуть маску по привычке и прошелся пару метров по открытому воздуху и такое блаженство и легкость дыхания. Где-то нас притисняют.  
*** Сопровод
Кинул Ане бумаги для работы в почте, дополнил их сопроводительным текстом. Она устроила истерику, что я не могу ей сказать голосом, что я от нее хочу. Истеричка хренова.  
*** Карантин
Пришел ака с карантина. В очереди на вход стоял до 11. Потом были бесконечные разговоры о ковидле. Разжирел на своем больничном. Почему-то все хвалятся, что 10 дней жрали элитное поило.  
*** Олени
Филип пришел в прикольной рубашке с оленями. Потом была плаксивая история про расстование.  
*** Ручка
Ручка двери работает все хуже и хуже. Прибегнул к последнему средству и попросил помощи у Димы. Я даже не заметил, как он пришел и все заработало. Мастер.  
*** Киноклуб
И рассказала, что ей понравились все рекомендации, что я ей давал. Сам попросил совета у Ильи в незнакомой для меня облости аниме. Может и нормальная тема кинофила.  
** 12.01.2021 Вт
*** Киберпанк
Дети с этими светоотражающими вставками в одежде создают унылому ночному городскому окружению немного киберпанковости. Очень эффектно
*** Пробка
Сегодня пробка оказалась еще длиннее и все парковочные места были заняты. Нам это не понравилось.
*** Отчеты
Что-то опять посыпалось как их ведра. Нихрена не готово, несмотря на подготовку за три масяца. Все сначала. Может перемены и к лучшему, хотя Ч не тот человек, который ведется на всю эту чепуху.
*** Сериальчик
Посушил мозг над Вустером. Милый забавный сериальчик и много естестенных костюмов. Но чудеса меня удручают там.
** 13.01.2021 Ср
*** Автоматизация
Мне бы сейчас очень пригодилась. Одно дело - создать БД, другое - заставить ее работать. Опять эти тонны перелопачивания одинаковых данных. Возлагаю надежды на нормальное программирование и интерфейсы. 
*** Черновики
Решил немного навести порядок. 7 пачек израсходованной бумаги. Полдня перекладывал эти бумажки. Ничего полезного. Надо с обновкой руководства обновить и программу экономии бумаги. 
*** Вики
У Мазая возникают странные вопросы про вики, впарил ему, что когда-нибудь это заработает. И еще немногр Жиры в положительном контексте.
*** Морозец
Кончики пальцев замерзли, я сильно задумался, что в детстве небыло такого понимания своего тела. Сейчас я принимаю сигналы и адекватно интерпретирую их. Моя обеденная прогулка по большей части была с замерзшими руками, но буквально за 15 минут до отхода на базу возникла точка перелома и стало тепло, можно было продолжить гулять до бесконечности.  
*** Утка
Готовил сегодня утку, гемора слишком много, удовольствия мало. В мультиварку она не влазела и пришлось сломать ей спину. Кожа жирная и перья торчат пеньками. Замориновать ее не удалось и пришлось делать так. Этот неприятный запах. Гусиное мясо гораздо вкуснее. Тут мясо сухое и жесткое. Никогда больше не покупать утку.  
*** Горелка
Насмотревшись повора, решил купить горелку. В магазине продовец нихрена не понимал и призрительно общался со мной. Не ходить больше в тот магазин. Попробовал жарить лук - не понравилось, вся концепция не понравилась. Эргономика отсутствует, вкусовых качеств не добавляет. Опасный предмет на кухне. Все так себе.  
*** Хлебцы
Нашел в магазине замену сухарей для Димки. Какие-то диетические хлебцы. Я не понял прикола, но Димка говорит, что эти даже лучше, чем дома. Ну и пускай ест их. Я продолжу питаться нормальными добротными сухарями.  
*** Прививочник
Димке сделали прививку от столбняка и он весь вечер жаловался, что у него болит под лопаткой. Почему мне не деалили их никогда, я не знаю.  
*** Ремешок
Забрал с почты ремешок. Резина жесче и есть зазор при монтаже. Нет всех этих предупреждений. Оригенальный был интереснее. У часов все равно уже дохнет акб. Но так (с неиспорченым ремешком) гораждо приятнее, да и разъем питания теперь защелкивается как влитой.  
*** Пурга
Погода разыгралась не на шутку. Местами запорошило всю дорогу. Залипали в окно минут пятнадцать как там "буря мглою небо кроет". Давно не было такой ненастной погоды.  
** 14.01.2021 Чт
*** Запаренный
Кн вызвал меня вечером, когда я уже собрался уходить. Поныл на свою сложную жизнь. Я сообщил что "все фигня - прорвемся" и со спокойной душел пошел домой.  
*** Метафизика
Дугин против Переслегина. У одного мощная филосовская школа с знанием греческого и всех философов лично, у другого достраивание схем и новые смыслы. Я больше за Переслегинский вариант (надо найти книги по схемотизации). И тот и другой обогащают друг друга. Я же не понимаю и половины того, что они говорят.  
*** Пустые бабские разговоры
90% разговоров - полная фигня. Меня сильно раздражает близкие контакты И и Антона, но как показывает мой жизненный опыт - все это фигня и просто люди от безделия ищут общения, или я ничего не понимаю в жизни и так на пустых разговорах люди ездят по ушам и трахаются и потом страдают и это нормальная хреновая жизнь.  
*** Бритва Оккама
Приказ и сложные теории. Не подписывают приказ. Уже стали возникать теории, что это заговор. Потом прилетела доп.информация, что делопроизводитель заболела. Это рушит все сложные теории. Потом делопроизводитель сказала, что приказы не подписывают с 29 числа по непонятным причинам. Незнание порождает ненонимание и стресс. Люди сами накруживают себя. Так и с моей ревностью к И - Пустая ревность. 
*** Ютуб и пустота
Ничего интересного. Убитый вечер. 3х. И так все чаще. Это психологическое дрочево. Безрезультатная безцельная псевдодеятельность.  
** 15.01.2021 Пт
*** Отчеты
Охерели там со своими отчетами, только автоматизация нас спасет. Не успеваю охреневать от закидывания меня заявками на составление отчетов. И так уже несколько лет подряд и никакого профита.  
*** Кельберер 
Была придумана новая единица производительности труда - один кельберер - витрувианский инженер, средневзвешенный ведущий инженер. 
*** Интриган
Все у меня сегодня спрашивают, работаю ли я завтра - да.
*** Группы
Прям прошелся по своим группам, накидал пару интересных ссылок. Почувстовал жажду деятельности. Еще не все потеряно.  
** 16.01.2021 Сб
*** Работа
Работать в субботу - это полная фигня. Пол дня провозился с подготовкой данных. Существенно продвинулся, но морального удовлетворения не получил. Опять все занимаются своими делами. Надо на работе устраивать трахательные комнаты, что бы люди не отвлекались на работу и занимались своими делами.  
*** Комп
Пришел СС и попросил помочь с приказами. Я помог ему с вторым монитором и получил от этого кучу морального удовольствия. Работа со всем этим старым железом, улучшение эрогономики рабочего места, настройки и понимание того, что до меня это никто не сделал.  
*** Пенаты
Поехали в магазин за незамерзайкой. Дорога отрвратительная. Мазагин безлюдный, консультанты аж драться чуть не кинулись за нас от скуки. Ассортимент побольше, чем в Леруа. Толчки подвесные есть красивые. А вот раковины (точнее подраковенные тумбочки) мне не понравились. Магазин странный. Вообще не понимаю идею этих магазинов.  
*** Пурга
Погода отвратительная. Дорога вся занесена. Решили, что правильно поступили, что не поехали домой. Дорога скользкая и вообще лучше никуда не выходить. Мело весь остаток дня.  
*** Магазин
ДК перекрыт полностью, в соседних магазинах нет ничего приличного. Как-то грустно стало без привычных магазинчиков. Это активная политическая борьба с неугодными конкурентами.  
*** Карточка
Треснула антенка и карточка не работает как должна. Добрая женщина в магазине предложила вставить ее чипом и это помогло. До конца действия не дотянула пару месяцев. Не буду ее перевыпускать сам, пускай все идет своим чередом. Перейду на Мастре. Надо купить обложку для нее. 
** 17.01.2021 Вс
*** Велосипедисты
Наблюдал в окно велосипедиста. На улице -19оС. Это конечно не от хорошей жизни, но популяризация велосипедов меня больше радует, чем удручает. Но зимой кататься я не хочу.  
*** Отказоустойчивость
Надо придумывать такую систему снабжения, защищенную от отказа узловой точки. В окрестностях это более менее реализовано. Надо в квартиропоиске учесть и такой коэффициент, как устойчивость инфраструктуры (по магазинам, воде, электричеству). В соседнем супермаркетет все на взводе, покупатели на взводе (если закроют еще и этот - придется бегать по всему району и отказаться от привычных продуктов). Нашел орехи подешевле в полатке поближе, еще бы они поставили себе терминал.  
*** Разборки
Разобрался немного в делах. Но опять не успел сделать ничего. Этот ютуб отнимает чрезвычайно много времени. Хотя накопировал себе книг - читать не перечитать.  
*** Инстарис
Запилил прикольную гарбушу с рисом. Получилось замечательно. Аж решил сфотать ее в свою группу.  
*** Телевизор
Дома кончился телевизор. Надо бы не продлевать его, но что-то они там грустят без телека.   
*** Интернет
В магазинах нет ничего приличного. А в интернете уже гораздо проще купить всю эту мелочевку. Надо потренироваться в интернетмагазине. 
*** Программирование
Нашел прикольный канал с программированием - надо практиковаться. 
*** Серая зона
Знаешь человека много лет, а в интернете он совсем другой. И тут суровый мужик лайкает тортики, а циничная женщина - котиков, а мамы красивейшие картинки - никому нельзя верить, все надо парсить и анализировать, собирать собьективные субьективные сведения и проводить тестирование гипотез
** 18.01.2021 Пн
*** Делай добро и убегай
Наконец подписали приказ и я подкинул И ее экземпляр. Она поблагодарила меня конфеткой. Вот уж действительно "делай добро и убегай". Что за несправедливая жизнь.  
*** Наконец пришла зима.
Холодает. -21оС. Решил не идти домой пешком и дождался Димку (хотя можно было и прогуляться). Простоял дожидаясь его и еще стояли в пробке. Потом пошел в магаз по холодному воздуху. Так себе ощущуния
*** Чеклист
Подбил работы в табличку. Кн забрал ее себе. На следующий день подбил табличку на вики, Кн не оценил всей прелести (потомучто смотрит не в том браузере). Но мне табличка понравилась. Очень полезная.  
** 19.01.2021 Вт
*** Работун
Сделал сегодня вал работ, узнал что делаю дублированную работу, охреневаю от бездельников. И у меня возникают мысли работать с ними? Всех разогнать, кто не хочет работать.  
*** Сплетница
Появился в наших рядах сплетник, человек потерял всякое уважение в моих глазах. Всю дорогу до дома думал, как его уязвить так посмачнее. Когда пересекся с ним на следующий день, даже не обратил внимания, что он есть в комнате. Все эти бессмысленные обдумывания вариантов только вредят полноценному сну.  
*** Ошибки
Просил же проверить, эти бездельники бесполезны. Теперь исправлять ошибки. Забыл кавычки и теперь бумага выглядит как несуразица.  
*** Кельберер
Узнал, что производительность труда меряют в (рублей в час) (прибыли) и это очевидно просто. Ставим это в числитель, а интенсивность в знаменатель расходы (ЗП и накладные). Надо еще раз поштудировать старика Маркса.
*** Столовка
Открылся наконец малый зал, это божественнш, чистые ложки, теплая еда, приятрые люди, камерная обстановка
** 20.01.2021 Ср
*** Оперативное управление
Раскрасил табличку того, что надо сделать. Табличка в красном. Сделано почти нихрена. Кругом одни бездельники. 
*** Быка за рога
Когда вчера уходил, помохал в след уходящей И. Она пригрозила начать ко мне приставать, но утром, прямо с порога стала приставать скаким-то 1с. Утренний ликбез 1С привел меня к мысли, а не поучиться этому дрянному продукту. Общение с пятнашечниками оставило у меня только возглас "ебнутая пизда" для женщины которая позвонила по моему запросу на консультацию и сказала, что у нее нет сейчас времени.  
*** Прогулка
Безмашинное производство
*** Картошечка
Очень вкусная жаренная кортошечка. Давно о ней мечтал. А немного остывшая она просто бесподобна.  
*** 90 дней
ДК открылся обратно. Это прям облегчение от моей бананово сухарной ломки
*** Полуночник
Димка вернулся под вечер, когда я уже собирался спать
** 21.01.2021 Чт
*** Снежная борода
Поземка и мороз. Погода вообще странная. Негулябельно. Все дорожки занесло. 
*** Мотивация
Считалочка и сопротивление. Сделал ексель модель распределения премиального фонда. Получилось очень красиво и наглядно. Никто не в состоянии оценить ее прелесть. Пытался у Мотивационшиков спросить как это работат - они не знают. Марат обращался ко мне на Вы, другие просто узкие. 
*** Контраргумертация
Поти кинул мне работу, я чет вспылил и пошел козырями. Адреналил хлестал через край. День испорчен.  
*** Киндзадза
Большова встретилась в коридоре и предъявила на мое старое замечание про возможности почты. Она походу туповата. 
*** Лориенс Аравийский
Ты кто такой? Такой вопрос я услышал от Фили. Потом Кн спросил как нам от него избавиться)) И чтоб Мелю забирал (всех пришлых (а я еще бы сдал Поню))
*** Переработки
Пока обьяснишь все этим начальникам, уже переработал час. Конечно никто мне за него не заплатит. 
*** Ты проджект менеджер
В действиьельности все не так как на самом деле. Встретил Лешу, он рассказывал, что ровно было на бумаге.  
** 22.01.2021 Пт
*** Тепло
На улице оттепель, все тает. На фоне позувчерашних -20оС этот перепад просто невообразим. Дороги раскисли и проходимость срезко уменьшилась. Машины вязнут в снежной каше и шлифуют асфальт. Димка каждый раз пытается кинуть машину в занос и сегодня это получилось особенно сильно. 
*** Закрывушка
Успел сделать свою часть работы во время. Потом выяснилось, что с ошибками :) А руководство не справилось со своей работой. Предявил Филе, что он хреново работает, тот развопился, я ответил ему. Предъявил это Кн. Он схватился за голову и сказал, как бы убрать этих понаехавших. Ахаха. Моя пропаганда "всех уволить" приносит свои плоды. 
*** Неудобные вопросы
Накрутил вопросы про будущее - решил оставть их на послеаттестации, задал вопросы про адекватность - нет, было мне в ответ. Все вопросы, которые я задаю, вязнут в Лете. Бессмысленный диалог. 
*** Искры
Трамвайчик и столб искр. Возвращался из магазина, по раскисшим рельсам трамвая проехался этот самый трамвай. За ним на сварке рельсов столб искр и сердце убегает у меня в пятки. Димка сказал, что там всего 27 вольт (боюсь предположить, сколько там ампер). Очень странный транспорт.  
*** Лапочка
Пришел (точнее привела Мария) ко мне Лапочка, узнать, что делать с сетевым диском. Я решил прогнать на нем тест на профпригодность. И он его прошел. Есть еще вера в человечество. Потом эти имбицилы предъявляли, что я шлепнул визу на подотчетном мне документе. А Лапочка превратился в Евгения Владимировича. 
*** Пожарный
Нашел интересный канал про программирование на ВБА от пожарного. Сижу залипаю. Не думал, что "силовики" склонные к риску, могут так мастерски управляться простейшими пользовательскими инструментами, в то время как инженеры в ведущей компании пользуются компьютером, как печатной машинкой.  
*** Трикстер
Антон соблазняет меня переехать в лучшую половину комнаты. У меня зародились такие-же мысли. Только в болото.  
** 23.01.2021 Сб
*** Работа
Понесло меня на работу. Целый день убил на 5 из 25 табличек. Уже глаза на лоб лезут от этого всего. 
*** Пропаганда
Показал Игорю считалочку премий. Начал втирать ему про идеальное планирование. Заинтриговал ака, но ничего ему не показал. Если мои подсчеты верны, премия должна быть как вторая зарплата. Почему у меня за все время работы было только 2 таких выплаты, и они ни в одном месте не были похожи на вторую зарплату.  
*** Дождь
За окном идет дождь. Снежная каша на дороге превратилась в снежный суп. Вся трасса сырая и машины едут на облаках. От фур шлейф тянется на сотню метров. Зато машина не заляпана, а практически белая. 
*** Дом
Вместо того, чтобы чистить снег на придворовой территории для машины, мама просто утоптала всю площадку. Так получилось даже лучше. Снег дольше не растает. Нет этих гор отвала. Машина на маленькой подиуме. Дома хорошо. Выйдешь в сад, а там сад. Нужно минимум 8 соток пространства. Как же хорошо иметь частный дом. 
** 24.01.2021 Вс
*** Маленький принц
Утром проснулся раньше все и не смог быстро заснуть. Решил почитать. Достал Маленького принца и это просто офигительно. 
*** Туман
Не видно ни зги. Выехали немного попозже, думая, что туман рассеится. В районе он был метров 50, дальне немного рассеялся. По трассе машины летят, как срасть хотят. Сделал фотку где нет горизонта и нет дороги вперед. Вокруг вообще нет ничего, только лошадке хорошо.  
*** Женщина с машиной
При въезде в Тулу опять эта женщита стоит там уже 2 недели с открытым капотом. Подозрительно. Ржали долго.  
*** USB
Поставил ОС на 3.0 флешку и это вообще фиаско. За всю ночь ничего не обновилось. Не для этого система сделана. Теперь флешка официально переходит в разряд хранилища. Эта новость меня прям удручила. 
*** Беспокойство
Насмотрелся Школьникова про деньги и опять плохо работает флешочная ОС и начало трепать в груди, давление 161/97 чет высоковато. Плохо засыпал. Надо меньше смотреть про будущее. Оно неопределенно страшное. А потом думаешь про ограбление 91 и думаешь еще сильнее.  
*** Домики
Опять смотрел домики и это сплошное расстройство, информации нет, стоят дорого, все фигня. Может податься в деревню. 
** 25.01.2021 Пн
*** Ценовая политика
Вскрылось, что по работе надо сократьть расходы в 3 раза. Это уже ни в какие ворота. Надо всю концепцию переигрывать. А по другой работе заявили поминималками 0,2 млн. и мне сказали, что поднимут до 0,6 т.к. у них округление поднимит сумму до 1,0. Что-бы не писать округление вверх или вообще не округлять они готовы на порядок поднять затраты, я не понимаю.  
*** Протурбации
Договорился отдать на профилактику один комп и мне прилетела предьява, что я не спросил разрешения профилактировать чужой комп, потомучто на нем хранит свою нерабочую информацию другой человек. Я не понимаю.  
*** Прогулка
Вышел на обед попозже, а закончил есть синхронно с карп. Дошли до корпуса и пересекся с ИД. И позвала меня составить им компанию. Я с удовольствием это сделал. Просто светские разговоры. Но лучше, чем говорить с самим собой.  
*** SD
Провел эксперимент с карточкой и о чудо, обновление заняло всего час или полтора. Это реально рабочий вариант. Сама эта ОС мне вообще никак не понравилась. Заказал новую карточку, а эту пущу на эксперименты. Больше никогда не использовать ЮСБ в качестве железных устройств.  
*** Весна
И пришла в платье. Теплый воздух в лицо. Вскрылся асфальт. Как же хорошо. И это январь. 
** 26.01.2021 Вт
*** Поворот туда
На прогулке ИД совратили меня с пути и я потдался утехам живого общения. Переобулся на лету. Дальше светские беседы о былом. 
*** Человечки
Аф попросила помочь раскидать человечков. Сама сожгла слишком много человеков. Не видать нам баланса системы. 
*** Логистика на грани фантастики
Лена кинула на меня еще и организацию доставки бумаги, я помог ей с транспортом и послал нахрен, она пошла жаловаться на меня - смешные люди
*** Заложи начальника своего
По всем фронтам обрабатываю одного персонажа. 
*** Премии
Добился предварительного знания как считается премия. Не сходится с распоряжением. В три раза меньше, чем записано в законах. Не понятен механизм занижения. Все слишком непрозрачно.  
*** Грудастая ципочка
Димка походу наелся грудок, надо думать что-нибудь другое. Пол вечера орал как резанный, что грудка слишком жесткая. 
** 27.01.2021 Ср
*** Внезапная неожиданность
И отпросилась сегодня, а я сидел утром в надежде. Хотел срочно подписать бумаги, а Кн сегодня нет. Дима спирит позвал на ДРтортик, а я не пошел. Ака отпросился на завтра у меня.
*** Таблички
Подбиваю дебит и кредит и выходит какая-то лажа. Во всех работах концы не сходятся. Нет постоянного мониторинга. Нужно вводит системы ролинтехнолоджи. 
*** Дом
Посмотрел прогноз рынка недвижимости и дальше будет только хуже. Походу мой маятник качнулся в сторону дома. 
*** Жадина-говядина
Приготовил говядинки и она сегодня превосходна. В меру соленая. Варил ее полтора часа и буквально тает во рту. Надо чаще готовить говядину. 
** 28.01.2021 Чт
*** Отец героин
Ака слился, я его прекрывал, пиздлявый бабий язык его сдал с потрохами. А потом эти люди жалуются на бигбосов, что те сваливают по первому чиху. 
*** Шьёрт побьери
И сегодня опять нет, ходят слухи, что подскальзнулась, упала, очнулась, гипс. 
*** Карусель
Выехали в обычное время и пврковка была полностью забита, пришлось ставить в лесу на щебенку
*** Непорядочек
Пытался привести в порядок дела с человекоемкостью, а там уже резвится козел в огороде, разгребать эти авгиевы конюшни. А вообще надо написать считалочку версталочку до лета и использовать ее как аргумент
*** Высокое близкое
Посмотрел еще, Высокое ближе чем квартира от работы, быстрее бы весна и велоразведка
*** Перебезчик
Встретл чувака с этажа, тот переехал на соседнюю работу и хвалится, что там все круче и вообще медом намазано. Сдается, если через два с половиной года этот мир не рухнет, надо пересмотреть трудовую деятельность
** 29.01.2021 Пт
*** Бездельники
Что-то я разнервничался, когда эти нач.отдела не выполняют свою работу. Поспокойнее надо быть.
*** Профилактика
Отнесли компы на профилактику, цирк с конями - накрыть корпус крышкой и забыть
*** Календарик
По видимому календариковая промышленность не планировала 2021 год и достать приличный толстый перекидной - не такая простая задача.
*** Апгрейд
Флешка встала в фотик и теперь у меня 4к фоток в запасе, я конечно и 2 не набивал за поездку, но все-же. 32 флешку пущу на ОС.
** 30.01.2021 Сб
*** Работа
Опять поехал на работу. Все кругом не работают, хотя стоит это все в 2 раза дороже. Бесит. Написал служебку. Поправил таблицу. 
*** О Высоком
Уже несколько дней думаю о Высоком, как о альтернативе квартиры в Туле. Хорошая природа, частный дом, газ по забору. Отсутствует интернет, непонятно с водой и канализацией. Приемлемая цена. 
*** Ремонтер
У мамы сломалась стиралка. Димка засыпал лимонной кислоты и она заработала. Мама фигачила туда соду (советы из интернета) и все трубы закоксовались. 
*** Лемита
Дочитал "Маленького прица" и начал "Сумму технологиий" - наконец офигительная фантастика. Наконец я понял, за что Лема считают в ряду великих. 
*** ЗОлет
Кате 30 лет. Это уже как-то напрягает. 
*** 
** 31.01.2021 Вс
*** Снегочистка
Навалило снега и пошел чистить дорожки. Навык чистки снега утерян. Ломит спину на скручивание. Но сама идея прикольная.  
*** Алармист
Электронный термометр сломался и показывал -12. Папа с утра бегал и орал, что на улице ужас ужас. 
*** Занос
Снежная каша на дороге. По трассе пришлось уворачиваться от пидора обгонщака и пару колебаний машина совершила. На повороте в городе просто машину стало разворачивать. Страшное это мероприятие.
* Feb
** 01.02.2021 Пн
*** Показуза
Решил показать свои считалочки людям - люди - это тупые мрази. Никто нихрена не понял. 
*** Солнце
Красота утром, красота днем. Последние лучи солнца в лесу. Кросота. Все деревья в белом. Снег хрустит. Дорожки не чищенные.  
** 02.02.2021 Вт
*** Зараза
Анька самовыпилилась. Отвалилась ее поездка и у меня только сожаление, что ее не будет меньше, чем запланированно. Боже как же хорошо без этого бесконечного радио. 
*** Пусть с другим она гуляет
Опрокинули с доброй традицией. Д скинули на командировку, и И ушла гулять с Антоном. На пересечениях я просто продолжил свой путь в одиночестве. 
*** Счетчики
В то время как другие мечтают, я считаю. Игорь пожаловался, как бы нам посчитать деньги. Я тыкнул его носом в считалочку. Все покивали и проигнорировали. Пришла настоящая смета и там нашли замечания. В моей никто не смотрит ничего. Просираем сроки и прикидываемся, что не умеем считать. Идиотизм. 
*** Кускус
не удался. Просто подгорело. Надо попробовать не на ребрышках. Идея тоже так себе. Просто макароны. 
*** Солнце
** 03.02.2021 Ср
*** Совещание
Тупость и порожняк. То, что можно решить за одну секунду и договориться за минуту, тянется уже три месяца и ничего нового не рождается. Мозговые слизни поразили всех вокруг.  
*** Расчеты
Люди тупые. Никто нихрена не слышит. Без теории нам конец. 
*** Подпись
Забыл, что сегодня среда, за сб расписалась И и я даже не вспомнил, за что надо расписываться
** 04.02.2021 Чт
*** Вежливость
фраера сгубила. Предложил Кате прогуляться в обед и она согласилась. Пол часа я был обречен слушать про непорядочек
*** Мисскоммуникация 2018
Как же тяжело с тупыми людьми
*** Мясо
Хотел сварить рис с рыбой, порылся в ящике и не нашел там риса. Пошел в магазин, накупил мяса и рыбы на 4кр. Принес домой рис и вот он лежит упаковка риса в ящике, точно такой же. Ну и хрен с ним, будет два риса.
*** Одежа
Собрался в магазин и оделся по быстрому, толстовка без майки, ветровка, чуть было не натянул ботинки без носок. Но нижнее белье не просто так придумали, без наго плохо совсем.
** 05.02.2021 Пт
*** Слишком сложно
Кн пожаловался, что мои отчеты ошибочны и слишком сложны - сделай все сам, мудила
*** Скользящие
Ака не явился сегодня, на меня льются всякие идиоты со своими идиотскими идеями
*** Халатность
Незадумываясь облакотился на сломанный стул, отбил плечо и отнес стул на 8, эти двое недоделков развопились, что это их гавно и они его еще недоели.
*** Стейк-миньён
Запилил вкуснотищу. Еще перетерли с И проблемы рынка и питания. Когда речь зашла о пище духовной, я рассказывал о будущем, которое будет, а она о романах.
*** Довоз
Антон посигналил, когда я шел домой, и предложил подвезти. Я кивнул, что хожу не потому-что не начем ездить, а потому-что гуляю
*** Время вверх
Насмотрелся Дугина и его пересказ концепции вертикального времени. Будущее на ступени выше, прошлое - инферно, настоящее - настоящее. И очень мне эта концепция понравилась. 
** 06.02.2021 Сб
*** Разрыв шаблонов
Пришел на работу, по пути догнал Кар. Но дверь в кабинет закрыта. Открыл, переоделся и пошел в женскую половину, а там пустота. Что делать, такова жизнь. Опять парочка ворковала весь день и смотрели фильмы целый день из одного наушника. 
*** Ступеньки
Насмотрелися ютуба и решил дернуть 14 этажей зарядку. Ноги слегка зибились. Надо попробовать продолжить эту тренировку. 
*** Расчеты
Долго думал, чем бы заняться, решил заняться объединением механизма планирвания и сжигания трудоемкостей. Запилил прикольную таблицу, порадил еще немного интересных мыслей по поводу управления. 
*** Заносы
Поехали домой. Солнце лежит прямо на горизонте. Как только въехали в район на дорогах появились заносы и поземка. Уже на апендиците дорога разлинована на три калеи и во время обгона машину немного занесло, стремно. Двор не чищенный, а утоптанный, а у ворот расчищено и перепад сантиметров в 30. Приехали в четыре, посмотрели сериальчик, в шесть все еще было светло, к девяти мороз уже был под 20 градусов. Красотища, прямо вечера на хуторе близ диканьки. Еще один повод брать частный дом. 
** 07.02.2021 Вс
*** Анализы
Мама предложила сдать анализы на онкологию. Как-же это все странно. Сдал образцы. Теперь думаю об этом. 
*** Лем
Бахнул вторую половину книжки. Теперь вся фантастика - тусклая калька с этих рассуждений. Наконец я полюбил читать Лема. 
*** Солнце
Погода прелесть, немного холодновато.
*** Высокое
Ссылаясь на хорошую погоду, пошел гулять до Высокого. В лесу шикарно. Погода прекрасна. Новое село скучновато, газ есть, дороги чищенные через одну. Половина домой недостроена. Натоптал ноги и изрядно замерз. Нет ощущения родного. 
** 08.02.2021
*** Месяц
На улице 17 градусов, чистое небо и почти растаявший старый месяц на горизонте
*** Аутсорс
Подрядил Марию править код. Боже, как удобно делать все несвоими руками
*** расчихан
Димка с сопляси и заразил меня
*** Лошадка
Вечером только и рассказывал анекдоты про лошадей
** 09.02.2021
*** Секвенция
Урезаю людям зарплаты, в первую очередь себе.
*** Имбицил-программист
Зашел в пятнашку и за три предложения унизил человека, живущего в двацатом году
*** Староверы
Пытались с Марией запустить софтину на ДОС. Это боль и страдания. Дискета завелась только в ее руках. Софтина завелась в бат но не завелась в ехе. Решили, что на сегодня хватит.
*** Унижения
Подставил Андрея и слился, тритировал Геннадия, обвинял в лицемерии Аркадия, защищая Антона (пустое место) обвинил И в необоснованности, разрубил гордиев узел в инсенуация И от Ака анекдотом про беспорядочрые половые связи
*** Люди для себя
Стал склорять К к деторождению и семейным ценностям и натолкнулся на сказки о прекрасром будущем и жизни для сабя
*** Нервная сеть
Димка мечтал, когда нейросети будут снимать кино по кригам, я сказал, что у каждого в голове есть такая нервная сеть, но его почемуто ракой ответ не устроил
** 10.02.2021
*** Недосып
Из за заложенного носа не спал с 2 до 4, кроме общего неадекватизма от простуды не чувствую усталость от недосыпа
*** Алармисты
И сразу заподозрила меня и отправила в больнрчку
*** Додельный
Доделал все срочные дела и слился от всякой ереси. Гнида недоделанная манипулирует и склоняем меня к программизму на матлабе, но по мне лучше программизм на человечках - непроторенная тропа, темболее качество наших начальников оставляет желать лучшего.
*** Кружки
Помыл чайные кружки. теперь в них можно смотреть на звезды, а не черная дыра, что была раньше
** 11.02.2021
*** Отсыпной
Выспался наконец-то
*** Порядочек
Как божественно приятно заниматься своими делами
*** Архив
Нашел таки утеряный архив моих старых работ
*** БП
Нарисовал Димке коробочку под блок пиитания, получилось очень хорошо.
** 12.02.2021
*** Пурга
На улицу страшно выходить, метет уже целый день и обнщают до понедельника, дома завалило по окна, город в пробках
*** Уборка
Немного подмел, купил коврик доя ванной, 
** 13.02.2021
*** Сон на животе
Поспал на животе и это так неудобно - весь вес тела отлеживает грудь и все затекает и шея неудобно, а еще пару месяцкв назад я только такой метод и практиковал
*** Линзы
Достал из своих старых закрамов линзы - у меря офигительная коллекция стекол.
*** Солнце
После таких снегопадов оород встал и красиво освещается солнышком
** 14.02.2021
*** Досуг
Посмотрел лекцию, как проводить досугипо Аристотелю - поспал на ней - очень хорошая лекция, очень полезный досуг
*** МОБ
Наткнулся на очередную эзотерическую концепцию с табличками
** 15.02.2021
*** Синий
Встал утром и в окне узрел идеальный синий, потом днем этот цвет неба менялся, но всеже оставался прекрасен
*** Выписка
Пошел и выписался с больничного. Переучелся с Воловской поликлиники на местную. Встречил коллегу. Место так себе
*** З/Работа
Ака позвонил узнать что как, это так подозрительно.
*** Сон
Поел вкусную пшенку с тыквой и вырубился спать
*** Предел безделия
Стало скучновато. Может и правду сокращать рабдень.
** 16.02.2021
*** Мороз
-22
*** Разрядка
встретил какого-то бомжа и тот сказал, что наша работа выполнена.
*** Повелеваю
Кинули мне еще какую то работу, которую я не делал. Надо разбираться
*** Закат
Шел домой в прекрасный закат, подсвеченный дым из труб, рассеяный свет
*** Контроль
Мама палит в камеры каждый чих
*** Деревенщина
И саазала, что мне надо отдохнуть за границой себя
*** Евангелисты
Дима подцепился к моей основной грппе
*** Банк
Стряс денек с народу на 23 - бумажные деньги уже ни с кого не стрясти.
*** Цифровизация
Дмитр попросил меня загнать всех бездельников под контроль
** 17.02.2021
 
