* Jan
** 01.01.2021 Пт
*** Ледяные цветы
Абсолютно все зашито в ледяно понцирь. Туман осаждает на деревьях и цветах иней и они превращаются в ледяные цветы. Каждый раз выходя из дома попадаешь в зимнюю сказку.  
*** Сериальчики
Занимали день сегодня безудержным просмотром сериалов. Один безинтереснее другого. В это время каждый занимался своим делом. Мама разгадывала сканворды, Димка играл в Факторио, я читал книжку. Папа спал.  
*** Реклама
От безделья понесло меня в Ютуб на телефоне. О ужас. Я узрел рекламу. Это отвратительная мерзость. Как люди вообще сидят не в Опере. Блаженные в своем неведении люди смотрят ютуб с этой рекламой. Я то думал, что мерзость, это когда ведущие непосредственно рекламят свякие игрушки и голосом рассказывают как они там что-то делают, но это было лишь вершиной айсберга. Ютуб сам суют каждые 5 минут левую рекламу - это ужасно. Жду недождусь, когда вернусь к просмотру ютубчика в Опере.  
*** План А
Начал читать "Республика Волмарт" и это вызвало у меня прямые асоциации для лого одной из моих групп. По приезду к нормальному компу надо будет перерисовать в нормальных скруглениямх и цеветах. Но пока пятилучевая звездочка (мир без звездочек) и градиент перехода (как в загрузке (только я ошибся и нарисовал градиент в другую сторону). Символизируют загрузку новой SocOS.  
** 02.01.2021 Сб
*** Отвертка
Просятил Димук, что в Никоновских объективах морочкик в фотике и крутится там отвертка. Почему они такие дорогие, мы не придумали.  
*** Снежки
Димка пошел приклеивать градусник и зарядил снежки в рабицу. Получились прикольные дыры в ледяном панцире сетки. Выглядело более чем эффектно.  
*** Чтиво
Практически весь день придавался чтению Волмарта. Не Стивенсон конечно, но годнота.  
*** Сериальчик
Посмотрели Звездный путь. Кругом сплошная политкоректота, но с фантастической точки зрения никакой.  
** 03.01.2021 Вс
*** Арома
Обновил еще один балон масляной мяты, разлил балон спиртовой мяты и балон дегтя. Может показаться странным, но это работает (пока не доказано обратное).  
*** Горизонт
Когда поехали, были прикольные виды с снежными тучами и самосветящимся горизонтом. Четкое разделение неба и земли застовило задуматься "как давно я вообще видел горизонт". Деревья в ледяных панцирях и грязная дорога.  
*** Непрядва
Заехали за Катей. Там бабская суета и Леша жарит шашлык. Катя набрала тяжеленную сумку. Степка уже указывает, что надо закрыть дверь. Все хорошо. Мама просила сфотать речку.  
*** Тула
Приехали. Тут грязища. Скука скучная и единстенное развлечение - компьютер. Надо переводить этот инструмент из разряда развлечений в дело.  
*** Дугин
Это прекрасно. Посмотрел НГ обращение Дугина на Авроре и просто катался по полу от смеха. Один из немногих русских философов современности цитирует мемасики и призывает читать классиков. Он шикарен.  
** 04.01.2021 Пн
*** Отпросилась
Погда я еще спал, но уже успел заварить чаек и залезть в ВК, мне написала И, и сообщила, что не придет сегодня, и ей слишком лениво. Я что-то прям расстроился и решил пойти в спортивной одежде и вообще отмести любые приличия и деградировать. Я удручен.  
*** Работа
Пропуск сразу не сработал и решил пропустить меня только с третей попытки. Предъявил на входе банан. Работа внеурочное время так себе. Мой приказ так никто не подписал. С бездельниками надо что-то делать. Серегин пришел ко мне в надежде, что я сегодня не работаю. Ходили толпы бездельников рассказать свою душещипательную историю про новый год.  
*** Семейные ценности
Часть команды расскзал, как сделал предложение своей девушке (с которой 9 лет), Илья - про то, что пора бы и к ней съездить на НГ. Макс - про то, что пора завести детеныша и что у него что-то не получается, Алексей - что он включил перфоратор, Аня - что бухала и бухала. Что-то мне эти разговоры не нравятся.  
*** Чтение
Нашел там книжку с ноута. Уж очень это неудобно. А еще толпы болтающих бездельников. Прочитал только пятую часть. К обеду от бездвиженного сидения уже стало все затекать.  
*** Макадамия
Макс посоветовал орехи. Бербраер их тоже нахвалилва. Купил попробовать. Первый - приольно - новый вкус и приятный запах. После третьего это стало просто неинтересно. Взвесили вес ядрышка к скорлупке и получилось чистая цена 5000 за кило - наркота походу дешевле. Мне не понравилось.  
*** Перехват
Шел с работы. Поболтал с мамой. Смотрю - машина меня дожидается. По номерам что-то знакомое - ну я и сел. Первый раз мы с Димкой пересеклись.  
*** Вибрация
Сходил в магазин, а Димка все еще на парковке с открытым багажником и счастливым (катарсис) лицом. Оторвана панель у багажника и там проводок, который скорее всего трется. Он нашел эту сволочь. Счастливый перетянул все паралонками. Теперь осталось проверить.  
*** Тыква раздора
Приготовил овощное рагу и кинул туда тыкву. Димка стал мрачнее тучи. Ну да, что-то не очень прикольный рецепт.  
** 05.01.2021 Вт
*** Обыденность
И пришла на работу. Антон пришел на работу. Опять эти их семейные ссоры. Прям градус интереса к ней сразу поубавился. Все уже было.  
*** Ветер перемен
Второй раз проскочил слух, что Кн смещают и Ч бедет за него. От этого у меня прям прошла досада от бессилия что-то делать. Все наработки коту под хвост. Надо с этим что-то делать.  
*** Календарик
Запилил И календарик с зубренком. Но мне не нравится на сегодняшний день верстка. Надо что-то думать друге. Вышел распечатать, И разговаривала по телефону у принтера, попросил ее подождать и болтали пока печатается, что-то проскочила боль в груби, было бы не очень красиво грохнуться в такой красивый момент.
*** Финвиз
Скачал нормальные .csv финтрат. Данные гораздо интереснее, но не полные. А еще посмотрел в ЛК траты по дням и офигел слегка. В день по 500-1500. Всего за 2020 250кр затратных. 
*** Преподство
Что-то на волне вчерашних разговоров про семейственность у меня все чаще проявляется непреодолимое желание кого-то учить и властвовать безраздельно. Сегодня посмотрел еще Дугина и это просто прикольно - под старость надо переходить в преподство. Чувак шарит и еще и в теме. Аж подписался на него в ВК.  
** 06.01.2021 Ср
*** Головомойка
Устроили головомойку Ане, сколько желчи и неприязни вызывает эта девочка.  
*** День живота
До этого брал с собой в обед бананы. Сейчас взял картошечку с красной рыбкой. Потом дома набился живот. 
*** Слухи
Озвучил слух по поводу кадровых перестоновок и прям за 15 минут волна женской слуховой сети развеяла слух переведя его в раздел слухов.  
*** Сериальчик
Наткнулся на старинный британский сериал, за вечер осилил 2 сезона. Закончил смотреть в час ночи. Нихрена не выспался. Но сериальчик прикольный.  
*** Чтиво
Дочитал Волмарт. Полнейшая хрень. Хотел поискать что-то еще в чтиво, но сериальчик пересилил меня.  
*** Пенопласт
Димка решил, что звук в комнате проводит дверь. Накрутил на нее пенопласт и думает, что это сработало.  
*** Пароль
Пол дня И и Антон шептались. Решил присоединится к ним. Там просто светские разговоры. Но уровень их общения похож на старую семейную пару. Этот выпендреж Антона и усипуси И. И знает его пароль в телефоне (0356) и они пользуются общими ресурсами. Вместе делят еду. Вместе куда-то гуляют на долго. Меня это бесит.  
*** 50 мм
Смотрел старые семейные фотографии, снятой еще на "смену" (40мм) и прям совершенно необычный эффект всего близкого. Все крупно и детально. Надо быстрее покупать полтинник и пробовать что-то творить
** 07.01.2021 Чт
*** Мойка
Поехали домой. Дорога отвратительная. Димка решил помыть машину. Пол дороги брехал и заставлял меня найти в неработающем интернете, есть ли в Волове мойка. Такой чистой машина не была с конвеера.  
*** Головняк
Что-то меня вырубило после дороги и теперь болит голова.
*** Белое
Такой красивый иней. Рабица и деревья. Все вокруг.
** 08.01.2021 Пт
*** Когнитивное невосприятие
Смотрели "Экспансию" и прям несоответствие брасаются в глаза и теранят мой мозг. В книге более сильные сюжетные повороты и совершенно иные персонажи. В сериале все топорненько подогнано для туповытых зрителей и сокращенное время повествования.  
*** Головняк
Болит голова весь день. Мама сказала, что у нее тоже - у меня прям сразу отпустило.  
** 09.01.2021 Сб
*** Сериальчики
Целый день гоняли сериальчики. То один, то другой. Что-то такое себе времяпрепровождение. За эти 10 дней практически потратил весь 11 ГБ трафик в интернете, впервые за все время пользования телефоном.  
*** Холодная оттепель
Весь день ждали -30оС, а на улице лишь капало с крышь и слоился туман.  
** 10.01.2021 Вс
*** Тула
Поехали в Тулу. Вся машина обледенела коркой. Дворники не работают как надо и всю дорогу я смотрел на мутное пятно перед собой и белый горизонт в боковом. В Туле вообще грязища. 
*** Кино
Посмотрел "Неадекватные люди 2" и прям норм. Первый поинтереснее, а тут девка сама дура. А психолог героически всех спас, хоть и не так как мог. Задуматься заставляет.  
** 11.01.2021 Пн
*** Бездник
Илья проставился за ДР. Поели пирожек. Очень по семейному. Там на верху только и разговоров, что о COVID. Тортики вкусные, но никакого ощущения праздника.  
*** Свободное дыхание
Забыл натянуть маску по привычке и прошелся пару метров по открытому воздуху и такое блаженство и легкость дыхания. Где-то нас притисняют.  
*** Сопровод
Кинул Ане бумаги для работы в почте, дополнил их сопроводительным текстом. Она устроила истерику, что я не могу ей сказать голосом, что я от нее хочу. Истеричка хренова.  
*** Карантин
Пришел ака с карантина. В очереди на вход стоял до 11. Потом были бесконечные разговоры о ковидле. Разжирел на своем больничном. Почему-то все хвалятся, что 10 дней жрали элитное поило.  
*** Олени
Филип пришел в прикольной рубашке с оленями. Потом была плаксивая история про расстование.  
*** Ручка
Ручка двери работает все хуже и хуже. Прибегнул к последнему средству и попросил помощи у Димы. Я даже не заметил, как он пришел и все заработало. Мастер.  
*** Киноклуб
И рассказала, что ей понравились все рекомендации, что я ей давал. Сам попросил совета у Ильи в незнакомой для меня облости аниме. Может и нормальная тема кинофила.  
** 12.01.2021 Вт
*** Киберпанк
Дети с этими светоотражающими вставками в одежде создают унылому ночному городскому окружению немного киберпанковости. Очень эффектно
*** Пробка
Сегодня пробка оказалась еще длиннее и все парковочные места были заняты. Нам это не понравилось.
*** Отчеты
Что-то опять посыпалось как их ведра. Нихрена не готово, несмотря на подготовку за три масяца. Все сначала. Может перемены и к лучшему, хотя Ч не тот человек, который ведется на всю эту чепуху.
*** Сериальчик
Посушил мозг над Вустером. Милый забавный сериальчик и много естестенных костюмов. Но чудеса меня удручают там.
** 13.12.2021 Ср

