* Jan
** 01.01.2021
*** Ледяные цветы
Абсолютно все зашито в ледяно понцирь. Туман осаждает на деревьях и цветах иней и они превращаются в ледяные цветы. Каждый раз выходя из дома попадаешь в зимнюю сказку.  
*** Сериальчики
Занимали день сегодня безудержным просмотром сериалов. Один безинтереснее другого. В это время каждый занимался своим делом. Мама разгадывала сканворды, Димка играл в Факторио, я читал книжку. Папа спал.  
*** Реклама
От безделья понесло меня в Ютуб на телефоне. О ужас. Я узрел рекламу. Это отвратительная мерзость. Как люди вообще сидят не в Опере. Блаженные в своем неведении люди смотрят ютуб с этой рекламой. Я то думал, что мерзость, это когда ведущие непосредственно рекламят свякие игрушки и голосом рассказывают как они там что-то делают, но это было лишь вершиной айсберга. Ютуб сам суют каждые 5 минут левую рекламу - это ужасно. Жду недождусь, когда вернусь к просмотру ютубчика в Опере.  
*** План А
Начал читать "Республика Волмарт" и это вызвало у меня прямые асоциации для лого одной из моих групп. По приезду к нормальному компу надо будет перерисовать в нормальных скруглениямх и цеветах. Но пока пятилучевая звездочка (мир без звездочек) и градиент перехода (как в загрузке (только я ошибся и нарисовал градиент в другую сторону). Символизируют загрузку новой SocOS.  
** 02.01.2021
*** Отвертка
Просятил Димук, что в Никоновских объективах морочкик в фотике и крутится там отвертка. Почему они такие дорогие, мы не придумали.  
*** Снежки
*** Чтиво
*** Сериальчик
** 03.01.2021
*** Арома
*** Горизонт
*** Непрядва
*** Тула
*** Дугин
** 04.01.2021 Пн 004

