* Jan
** 01.01.2021
Ничего не вспоминаю
** 02.01.2021
Квартирование в командировке. Всю ночь пытался разобраться где кого квартировать в командировке. И немного командировочных хлопот.  
** 05.01.2021
Пока досыпал утром наснилось коллеги скачащие как черти и всякое мракобесие
** 09.01.2021
Искусственные люди и отель над побережьем, расследование выбрасов с металургического
** 10.01.2021
Выживание как в сталкере и все последнее время у меня барахлил автомат и некоторые текстуры были непроходимыми
** 16.01.2021
Матвеев влепил мне 2 по спецглавам математики и это щенячее чувство обиды
** 19.01.2021
Бкхали с Катей шампанское на каком то складе, где она начальница и жаловались на тупость подчиненных и начальников, потом быстро переехали в студенческий класс, где сдавали начерталку и там было много красивых студенточек
** 20.01.2021
Выбирал дом на берегу реки и возвращался на автобусе который захватили амазонки, пришлось их вырубить всех. Будучи китайкем ехал на яхте в роскошный греческий дворец, где с помощью оползня в водопаде спас человечество от ядерной бомбы.

** 24.01.2021
Опять я за учебной партой. Извиняюсь, что не стрижен уже четвертую неделю. Препод по социопсихофилософии втирает какую-то дичь. Я как матерый раздолбай ничего не записываю, а потом понимаю, что ни не понимаю. Все мои записи превращаются в интерактивные образы.
