* Jan
** 01.01.2021
Ничего не вспоминаю
** 02.01.2021
Квартирование в командировке. Всю ночь пытался разобраться где кого квартировать в командировке. И немного командировочных хлопот.  
** 05.01.2021
Пока досыпал утром наснилось коллеги скачащие как черти и всякое мракобесие
** 09.01.2021
Искусственные люди и отель над побережьем, расследование выбрасов с металургического
** 10.01.2021
Выживание как в сталкере и все последнее время у меня барахлил автомат и некоторые текстуры были непроходимыми
** 16.01.2021
Матвеев влепил мне 2 по спецглавам математики и это щенячее чувство обиды
** 19.01.2021
Бкхали с Катей шампанское на каком то складе, где она начальница и жаловались на тупость подчиненных и начальников, потом быстро переехали в студенческий класс, где сдавали начерталку и там было много красивых студенточек
** 20.01.2021
Выбирал дом на берегу реки и возвращался на автобусе который захватили амазонки, пришлось их вырубить всех. Будучи китайкем ехал на яхте в роскошный греческий дворец, где с помощью оползня в водопаде спас человечество от ядерной бомбы.

** 24.01.2021
Опять я за учебной партой. Извиняюсь, что не стрижен уже четвертую неделю. Препод по социопсихофилософии втирает какую-то дичь. Я как матерый раздолбай ничего не записываю, а потом понимаю, что ни не понимаю. Все мои записи превращаются в интерактивные образы.

** 15.02.2021
Дважды И сегодря была застата в неблапопристойных занятиях у маня в саду, первый раз в бане, а второй отдрачивала ака, на мое "я тоже хочу" заявила, что у нее алергия. Это уже не в какие ворота.

** 19.02.2021
Обсуждали какие-то светские разговоры на лавочке в парке и И расслабилась, начала немного заигрывать, сняла футболку, и начала стягивать шорты - это было возбудительно

** 02.03.2021
Война

** 19.04.2021
Опять ИД лечили меня и бегали пол сна

** 28.05.2021
Урок английского, к аудиочасти которого я опять не готов и в утишение утешить и с засветами без смущения

** 29.05.2021
Тяжелые мысли про войну и прочее

** 01.06.2021
Искал место для дома. Катался по полям на велике. Красота. Из полей через промзону в сити.

** 30.06.2021
Встретились ребята с физтеха, очень рад их видеть

